intel/vaapi-fits

.slashrc
lib/common.py

Add --ctapr (call timeouts allowed per run).  If this limit
is reached in any single run, then all calls to the "call"
function will be rejected for all of the remaining tests.
Add --ctapt (call timeouts allowed per test function). Similar
to --ctapr, except the limit is only tracked on a per test function
scope.  For example, if test/ffmpeg-vaapi/decode/vp9.py:test_default
produces enough call timeouts to reach this limit, then all
remaining variations of this specific test function will not
succeed in a call to the "call" function.
--ctapr and --ctapt limits are only enforced in the scope after
test_start() and until test_end().

Add options to limit the number of allowed call timeouts

---

baseline/default
lib/metrics.py

Gstreamer does not have a way to limit the number
of decoded frames in the output.  Therefore, the
checksum was calculated on the entire decoded output
file and not on the number of frames that were
specified in the user configuration.  FFmpeg, on
the other hand, can output num-frames as requested
by the user configuration... and therefore, the
checksum is actually based on the number of frames.
This makes it difficult to easily compare between
all middleware to ensure they are properly producing
the same bitmatch decode output.
Change the md5 metric to only calculate the checksum
on the number of frames that were specified in the
user configuration.
Also, update gstreamer decode baselines accordingly.
Now checksum references are the same between the
ffmpeg and gstreamer decode cases, as …

Only calculate checksum on num-frames

---

.slashrc

Ensure test case names conform to slash's printable values to avoid arbitrary and generic test name.

validate test case names

---

README.md

switch to directing people to http://intel.com/security 
rather than 01.org’s secure-opensource@intel.com
(That’s a recent policy change)

switch to directing people to http://intel.com/security

---

test/ffmpeg-qsv/vpp/deinterlace.py
test/ffmpeg-vaapi/vpp/deinterlace.py
test/gst-msdk/util.py
test/gst-msdk/vpp/deinterlace.py
test/gst-vaapi/vpp/deinterlace.py

Refactor deinterlace tests to include interlace params
in the pipeline.  Also, set the default metric to use
md5 checksum (which can be configured in the user config).
The user config can set tff param:
0 = bottom-field-first
1 = top-field-first
By default, if tff is not set then 1 (top-field-first)
is assumed.
Fixes #4

vpp/deinterlace: set interlace pipeline params

---

lib/metrics.py

if the case set a param "numbytes = -1", it can
calculate the md5 of whole file directly

lib/metrics: calculate the md5 of whole file

---

test/gst-vaapi/encode/avc.py
test/gst-vaapi/encode/hevc.py
test/gst-vaapi/encode/jpeg.py
test/gst-vaapi/encode/mpeg2.py
test/gst-vaapi/encode/vp8.py
test/gst-vaapi/encode/vp9.py
test/gst-vaapi/util.py
test/gst-vaapi/vpp/brightness.py
test/gst-vaapi/vpp/contrast.py
test/gst-vaapi/vpp/denoise.py
test/gst-vaapi/vpp/hue.py
test/gst-vaapi/vpp/saturation.py
test/gst-vaapi/vpp/scale.py
test/gst-vaapi/vpp/sharpen.py

convert input format to NV12 before vpp so that it can be applied for iHD driver

gst-vaapi/vpp: convert input format to NV12 before vpp

---

test/ffmpeg-vaapi/encode/encoder.py

Since ffmpeg commit:
f4d7bd6cdbcf vaapi_encode: Support more RC modes
In ffmpeg, an "rc_mode" option was added to explicitly
set the rate-control mode.  If rc_mode is not specified,
then ffmpeg will try to auto-select the rc mode.
However, auto-select will choose AVBR over VBR if the
driver supports it.
Thus, set rc_mode explicitly to avoid auto-select.

ffmpeg-vaapi/encode: add rc_mode option to pipeline

---

baseline/default
test/gst-vaapi/decode/10bit/__init__.py
test/gst-vaapi/decode/10bit/hevc.py
test/gst-vaapi/decode/10bit/vp9.py
test/gst-vaapi/decode/avc.py
test/gst-vaapi/decode/decoder.py
test/gst-vaapi/decode/hevc.py
test/gst-vaapi/decode/jpeg.py
test/gst-vaapi/decode/mpeg2.py
test/gst-vaapi/decode/vc1.py
test/gst-vaapi/decode/vp9.py
tools/xform-baseline-1.sh

This improves code reuse and design for gst-vaapi/decode
tests.
10bit decode tests have moved into its own sub-directory.
Updated test names in baseline.
Updated tools/xform-baseline-1.sh script to convert old
baseline test names to new test names.

gst-vaapi/decode: refactor tests for better code reuse

---

test/ffmpeg-vaapi/decode/10bit/hevc.py
test/ffmpeg-vaapi/decode/avc.py
test/ffmpeg-vaapi/decode/hevc.py
test/ffmpeg-vaapi/decode/jpeg.py
test/ffmpeg-vaapi/decode/mpeg2.py
test/ffmpeg-vaapi/decode/vc1.py
test/ffmpeg-vaapi/decode/vp8.py
test/ffmpeg-vaapi/decode/vp9.py
test/ffmpeg-vaapi/encode/10bit/hevc.py
test/ffmpeg-vaapi/encode/avc.py
test/ffmpeg-vaapi/encode/hevc.py
test/ffmpeg-vaapi/encode/jpeg.py
test/ffmpeg-vaapi/encode/mpeg2.py
test/ffmpeg-vaapi/encode/vp8.py
test/ffmpeg-vaapi/encode/vp9.py

Using slash.requires at the class level causes the
requirement to be applied to all branches of the
entire class inheritance tree starting from the base
class.  This is problematic because if one requirement
is not met on a derived class, then every class that
is derived from the same base gets flagged for that
unmet requirement.
See https://github.com/getslash/slash/issues/928 for
more details about this issue.
Thus, move slash.requires to the test functions where
we intend for that requirement only to be used within
that scope.
Also, to be safe, don't use slash.tags at the class
level either.

test/ffmpeg-vaapi: do not use requires at class level

---

baseline/default
test/gst-vaapi/encode/10bit/__init__.py
test/gst-vaapi/encode/10bit/hevc.py
test/gst-vaapi/encode/avc.py
test/gst-vaapi/encode/encoder.py
test/gst-vaapi/encode/jpeg.py
test/gst-vaapi/encode/mpeg2.py
test/gst-vaapi/encode/vp8.py
test/gst-vaapi/encode/vp9.py
test/gst-vaapi/util.py
tools/xform-baseline-1.sh

This improves code reuse and design for gst-vaapi/encode
tests.
10bit encode tests have moved into its own sub-directory.
Updated test names in baseline.
Update tools/xform-baseline-1.sh script to convert old
baseline test names to new test names.

gst-vaapi/encode: refactor tests for better code reuse

---

baseline/default
test/gst-msdk/decode/10bit/__init__.py
test/gst-msdk/decode/10bit/hevc.py
test/gst-msdk/decode/10bit/vp9.py
test/gst-msdk/decode/decoder.py
test/gst-msdk/decode/hevc.py
test/gst-msdk/decode/jpeg.py
test/gst-msdk/decode/vc1.py
test/gst-msdk/decode/vp8.py
test/gst-msdk/decode/vp9.py
tools/xform-baseline-1.sh

This improves code reuse and design for gst-msdk/decode
tests.
10bit decode tests have moved into its own sub-directory.
Updated test names in baseline.
Update tools/xform-baseline-1.sh script to convert old
baseline test names to new test names.

gst-msdk/decode: refactor tests for better code reuse

---

test/gst-msdk/decode/decoder.py
test/gst-vaapi/decode/decoder.py

Add option "scale_output" to allow the test case config
to instruct the gst-vaapi or gst-msdk decode tests to
apply videoscale (SW scaling) to the output.  This is
mostly useful for testing decode cases where the input
file has multiple resolutions and we want decoded output
to be in a single resolution so that it can work with
certain metrics settings.
By default, ffmpeg automatically scales (SW scaling)
output (which can't be disabled, afaik).  Thus, ffmpeg
tests don't need to do anything with scale_output.

gst-vaapi/gst-msdk: add decode scaling option

---

test/ffmpeg-qsv/transcode/__init__.py
test/ffmpeg-qsv/transcode/avc.py
test/ffmpeg-qsv/transcode/hevc.py
test/ffmpeg-qsv/transcode/mpeg2.py
test/ffmpeg-qsv/transcode/transcoder.py
test/ffmpeg-qsv/transcode/vc1.py
test/ffmpeg-qsv/util.py

1. It supports transcoding of AVC, HEVC, MPEG2 and VC1 test streams
2. HWtoHW, HWtoSW and SWtoHW transcoding support added for ffmpeg-qsv

ffmpeg-qsv/transcode: Transcoding feature support

---

test/gst-msdk/decode/10bit/vp9.py
test/gst-vaapi/decode/10bit/vp9.py

gst/decode: mkv file extension added as supported decoding format

---

test/gst-vaapi/vpp/csc.py

The format property is an aberration and will likely be
deprecated in the near future.  The recommended method
for specifying output format is to use the srcpad format
caps method, instead.
See https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi/issues/142
discussion for more details.

gst-vaapi/csc: use srcpad caps to specify format

---

test/ffmpeg-vaapi/decode/decoder.py

There is no way to force ffmpeg-vaapi decode commands
to fail if SW fallback is used.  However, with debug
verbosity, ffmpeg logs will indicate when vaapi_vld
is chosen as the decode format.  The vaapi_vld format
is the indicator that HW acceleration is being used.
Thus, we should fail the test if vaapi_vld message is
missing to avoid test escapes.
Also see https://trac.ffmpeg.org/ticket/7519

ffmpeg-vaapi/decode: fail if SW fallback is used

---

lib/platform.py

See: https://github.com/intel/media-driver/issues/568

platform: enable iHD VP8 Enc tests on KBL+

---

test/gst-vaapi/encode/hevc.py

add lowdelayb=1 in gst-vaapi/encode/hevc.py cqp_lp
gst-vaapi hevc vdenc cqp/cbr/vbr need to add low-delay-b=1 in command line .  Previous I missed adding  in cqp_lp . I should check more carefully next time .

hevc vdenc: fix add missing lowdelayb=1 in gst-vaapi

---

.slashrc
lib/baseline.py

Metric keys (e.g. psnr) can be reused multiple times
in the same test case but in different context (e.g.
transcode 1:N tests).  Thus, include the context in
the key when setting metric test details so that
previous metric details are not unintentionally
overwritten in the test details dictionary.

Include the context (refctx) in metric test details

---

test/ffmpeg-qsv/encode/10bit/hevc.py
test/ffmpeg-qsv/encode/avc.py
test/ffmpeg-qsv/encode/encoder.py
test/ffmpeg-qsv/encode/hevc.py
test/ffmpeg-qsv/encode/jpeg.py
test/ffmpeg-qsv/encode/mpeg2.py
test/ffmpeg-vaapi/encode/10bit/hevc.py
test/ffmpeg-vaapi/encode/avc.py
test/ffmpeg-vaapi/encode/encoder.py
test/ffmpeg-vaapi/encode/hevc.py
test/ffmpeg-vaapi/encode/jpeg.py
test/ffmpeg-vaapi/encode/mpeg2.py

1. It supports AVC encoding for multiple iterations in single test run
2. md5 is used for validating each encode iteration

ffmpeg-vaapi/encode: R2R support added

---

test/ffmpeg-qsv/encode/encoder.py
test/ffmpeg-qsv/encode/jpeg.py
test/ffmpeg-vaapi/encode/encoder.py

Since f06ed1c4926b and 6eb8b07b1c17, the gen_name()
method no longer formats the return value for the caller.
The caller is responsible to format it.  This was not
accounted for in the check_metrics function where it
gen_name() is also used.  Fixed.

ffmpeg/encode: fix filename bug

---

test/ffmpeg-qsv/encode/encoder.py
test/ffmpeg-vaapi/decode/decoder.py
test/ffmpeg-vaapi/encode/encoder.py
test/gst-msdk/encode/encoder.py
test/gst-vaapi/encode/encoder.py

The first encode/decode command is always the same for first call in r2r and non-r2r cases.  Thus, share that code.  Also, cleanup other unnecessary complexities.

Consolidate common R2R vs. non-R2R code

---

test/ffmpeg-qsv/vpp/csc.py
test/ffmpeg-vaapi/vpp/csc.py

Fix incorrectly specified filter requirements for VPP CSC tests in ffmpeg-qsv and ffmpeg-vaapi.

Fix ffmpeg vpp csc filter requirements

---

test/ffmpeg-vaapi/encode/avc.py

ffmpeg-vaapi/encode: fix typo in test init

---

lib/metrics.py

This allows user config to configure psnr
as the metric for tests that support the
metric setting.

lib/metrics: add psnr to check_metric

---

test/gst-msdk/vpp/scale.py

Don't use videoconvert to do the scaling... it
defeats the purpose of the test.  Instead, scaling
should be tested with msdkvpp.

gst-msdk/vpp/scale: use msdkvpp for scaling

---

test/ffmpeg-qsv/transcode/transcoder.py
test/ffmpeg-vaapi/transcode/transcoder.py

According [VIZ-15572](https://jira.devtools.intel.com/browse/VIZ-15572) lizhong's comments
if add "-hwaccel_output_format vaapi" , thus means decoding output is working on video memory,  then hwupload is not needed. 
if remove hwaccel_output_format, vaapi decoder will output to system memory, then hwupload is needed.

ffmpeg/transcode: remove hwupload in hw to hw filter

---

test/ffmpeg-qsv/decode/decoder.py
test/ffmpeg-vaapi/decode/decoder.py
test/gst-msdk/decode/decoder.py
test/gst-msdk/util.py
test/gst-vaapi/decode/decoder.py
test/gst-vaapi/util.py

Decode tests already support optional sw scaling via `scale_output` setting in user config.  Add support to allow user config to optionally use hw scaling instead.
Now `scale_output` can be set to "hw", "sw", True, False where "sw" and True mean the same thing (for backwards compatibility).  Also, for sw scaling mode, ensure ffmpeg sets scale output to specified width and height.

Add optional hw scaling support to decode tests

---

.slashrc
lib/baseline.py

Allow user to specify a reference key in the
test case's refctx setting.  For example:
refctx = ["key:vp9.decode.10bit"]
will lookup the test case reference value with
the following key:
vp9.decode.10bit:<test_function(params...)>
This feature enables the ability to share a single
reference value (e.g. MD5) across different
middleware that implement the same test function for
each defined case (e.g. decode tests).

baseline: support for custom reference keys

---

test/ffmpeg-qsv/decode/decoder.py
test/ffmpeg-vaapi/decode/decoder.py
test/gst-msdk/decode/decoder.py
test/gst-vaapi/decode/decoder.py

scale_output is unnecessary for decoding

decode: remove scale_output support

---

test/ffmpeg-qsv/transcode/transcoder.py
test/ffmpeg-vaapi/transcode/transcoder.py

ffmpeg decode commands must have "-vsync passthrough".
Transcode include decode and encode.

ffmpeg/transcode: add "vsync passthrough" in command

---

lib/caps/ICL/iHD
test/ffmpeg-qsv/vpp/denoise.py
test/ffmpeg-vaapi/vpp/denoise.py
test/gst-msdk/vpp/denoise.py
test/gst-vaapi/vpp/denoise.py

On ICL, for both gstreamer and ffmpeg,
denoise will only influence Luma,
and for the other platforms Luma and Chroma both changed

vpp/denoise: add Luma into ICL denoise cap

---

lib/common.py
test/ffmpeg-qsv/transcode/avc.py
test/ffmpeg-qsv/transcode/hevc.py
test/ffmpeg-qsv/transcode/mpeg2.py
test/ffmpeg-qsv/transcode/vc1.py
test/ffmpeg-vaapi/transcode/avc.py
test/ffmpeg-vaapi/transcode/hevc.py
test/ffmpeg-vaapi/transcode/mpeg2.py
test/ffmpeg-vaapi/transcode/vc1.py
test/gst-msdk/transcode/avc.py
test/gst-msdk/transcode/hevc.py
test/gst-msdk/transcode/mpeg2.py
test/gst-msdk/transcode/vc1.py
test/gst-vaapi/transcode/avc.py
test/gst-vaapi/transcode/hevc.py
test/gst-vaapi/transcode/mpeg2.py
test/gst-vaapi/transcode/vc1.py

Higher resolution input cases tend to take longer to
execute and are more likely to timeout.  If several
higher resolution cases use up the ctapt limit, then
any pending cases will be denied execution when they
would otherwise finish before a call timeout.
Thus, sort the test case parameters such that lower
resolution input cases execute before higher
resolution cases.

transcode: prioritize low res inputs before high res

---

test/gst-msdk/transcode/transcoder.py
test/gst-vaapi/transcode/transcoder.py

For HW to SW cases, x265enc can’t accept format NV12,
so we may need to convert format for x265enc

transcode: convert format for x265enc

---

test/gst-msdk/transcode/transcoder.py
test/gst-vaapi/transcode/transcoder.py

For 4k clip, the queue is not able to contain
a whole frame with the default value, so set
queue buffer size to zero to fix this issue.

transcode: set queue buffer size to zero

---

test/ffmpeg-vaapi/decode/decoder.py

Add "-hwaccel_flags allow_profile_mismatch" to allow profile
mismatch for vaapi_decode to cover the "profile unknown"
clips which is not typically standard.
Fix VIZ-15451.
Signed-off-by: Linjie Fu <linjie.fu@intel.com>

ffmpeg-vaapi/decode: add -hwaccel_flags allow_profile_mismatch

---

lib/caps/APL/iHD
lib/caps/CFL/iHD
lib/caps/KBL/iHD
lib/caps/SKL/iHD
lib/caps/WHL/iHD

iHD only support res4K encode on Gen10- platforms,
iHD team will update its feature summary on github
Fixes #142 

Caps: fixed not support res8K enc issue on Gen10-

---

test/ffmpeg-qsv/util.py
test/ffmpeg-vaapi/util.py

add format "AYUV" for ffmpeg-qsv and ffmpeg vaapi,
because command-line need "ayuv".

ffmpeg-qsv/ffmpeg-vaapi: add "AYUV" for format map

---

test/gst-msdk/decode/decoder.py
test/gst-msdk/encode/encoder.py
test/gst-msdk/transcode/transcoder.py
test/gst-msdk/vpp/vpp.py
test/gst-vaapi/encode/encoder.py
test/gst-vaapi/transcode/transcoder.py
test/gst-vaapi/vpp/vpp.py

Add "dither=0" to allow gst-msdk decode a hevc 10bit file to
get the same md5 value with others,such as gst-vaapi and
ffmpeg-vaapi.
Signed-off-by: Zhang Yuankun <yuankunx.zhang@intel.com>

gst-msdk/decode: add a parameter for decode command-line

---

lib/caps/EHL/iHD

To add the vaapi-fits support for platform EHL
Compared to ICL, there are no any VME encode support (AVC/HEVC VME and VP8/MPEG2/MJPEG are not supported)

Platform ehl

---

lib/common.py
test/ffmpeg-qsv/encode/mpeg2.py
test/ffmpeg-qsv/vpp/denoise.py
test/ffmpeg-qsv/vpp/sharpen.py
test/ffmpeg-vaapi/encode/mpeg2.py
test/ffmpeg-vaapi/vpp/denoise.py
test/ffmpeg-vaapi/vpp/sharpen.py
test/gst-msdk/encode/mpeg2.py
test/gst-vaapi/encode/mpeg2.py

In python3, the '/' operator no longer takes the
range types into account.  Thus, introduce and use
a mapRangeInt method for tests that expect integer
range mapping.

use mapRangeInt for int ranges

---

lib/metrics.py

The different versions of the skimage nrmse functions
also have different norm_type parameter name.  Both
versions still default to "euclidean" normalization.
Therefore, there is no need to explicitly specify
this parameter.

lib/metrics: remove nrmse norm_type parameter

---

lib/baseline.py

json.encoder.FLOAT_REPR was removed in python 3.
To get similar functionality that works for both python 2
and python 3, we need to subclass json.JSONEncoder to
override the _floatstr method via _make_iterencode.

lib/baseline: fix rebase portability

---

baseline/default
test/gst-msdk/encode/encoder.py

If qpi and qpb is unspecified, then gst-msdk will
send 0 to MSDK.  However, MSDK treats 0 as an
uninitialized value and does not specify the behavior
for such value.  Thus, MSDK is free to choose/change
the behavior as it sees fit (which recently happened
and changed all the test results).
We already explicitly set the qpp in the test.
This adds an explicit setting for qpi and qpb, too.
Setting all qp's to the same value essentially makes
it roughly equivalent to gst-vaapi's init-qp
functionality and should guarantee no surprises if
MSDK decides to change the behavior for 0 qp's.
Unfortunately, this will require gst-msdk encode
test baselines to be rebased.

test/gst-msdk/encode: explicitly specify qpi and qpb in pipeline

---

test/gst-msdk/encode/vp9.py

The src caps of msdkvp9enc is video/x-vp9 which means raw VP9 stream, so
a muxer is required if we want to get a stream file.

test/gst-msdk/encode/vp9.py: Add muxer in command line

---

lib/caps/TGL/iHD

To add the vaapi-fits support for platform TGL
Compared to ICL, there are no any VP8 decode/encode
support;
In future: there will add 12bit decode/encode support
for hevc/vp9 and HEVC SCC for main/main10/main444
decode/encode support

platform: added TGL platform support

---

lib/framereader.py
lib/metrics.py
test/ffmpeg-qsv/util.py
test/ffmpeg-vaapi/util.py
test/gst-msdk/util.py
test/gst-vaapi/util.py
test/self/formats.py

Added the hevc 10bit 444 (Y410) decode support for
gst-vaapi/msdk and ffmpeg-vaapi/qsv

Added HEVC 10bit 444 decode support

---

test/ffmpeg-qsv/encode/vp9.py

enable vp9 8bit encoding(vdenc) test for ffmpeg-qsv.

vp9_lp enc:enable vp9_lp encoding for ffmpeg-qsv

---

test/ffmpeg-vaapi/encode/vp9.py

enable vp9 8bit encoding(vdenc) test for ffmpeg-vaapi.

vp9_lp enc:enable vp9_lp encoding for ffmpeg-vaapi

---

test/gst-vaapi/encode/vp9.py

enable vp9 8bit encoding(vdenc) test for gst-vaapi

vp9_lp enc: enable vp9_lp encoding for gst-vaapi

---

test/gst-vaapi/vpp/vpp.py

The width, height and format properties are being
deprecated.  Use a caps filter instead.
See https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi/-/merge_requests/289
NOTE: this also removes explicit width and height usage
for deinterlace cases.  Removing those parameters exposes
a possible issue with mpeg2 deinterlace that needs further
triage.

test/gst-vaapi/vpp: don't use deprecated properties

---

test/gst-msdk/vpp/vpp.py

YV12 output is supported in VPP since:
https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/merge_requests/1120
https://github.com/Intel-Media-SDK/MediaSDK/pull/2027

test/gst-msdk/vpp: remove YV12 output quirk

---

test/gst-vaapi/encode/10bit/vp9.py

enable vp9 10bit encoding(vdenc) test for gst-vaapi.

vp9_lp enc:enable vp9_lp 10bit encoding for gst-vaapi

---

test/gst-vaapi/encode/hevc.py

add vme "low delay b" implementation for hevc 8bit
yuv420 encode for gst-vaapi testing

gst-vaapi: add vme low delay b implementation

---

test/gst-vaapi/transcode/transcoder.py

Add hevc 8bit vme low delay b support for gst-vaapi
transcode implementation

Transcode: gst-vaapi hevc8 vme low delay b support

---

test/ffmpeg-vaapi/transcode/transcoder.py

Add hevc 8bit vme low delay b support for ffmpeg-vaapi
transcode implementation

Transcode: ffmpeg-vaapi hevc8 vme low delay b support

---

.slashrc

The built-in slash plugins don't play well with the
vaapi-fits framework.  For example, xunit plugin does not
escape and "stringify" attributes and values.
Thus, uninstall the built-in plugins since we won't
support them.

slashrc: uninstall built-in slash plugins

---

test/ffmpeg-vaapi/encode/encoder.py

ffmpeg-vaapi added new seperate output print log
for hevc 8/10bit low power mode, which is "Using
intra and low delay B-frames"

ffmpeg-vaapi: seperate ipb mode check for hevc lp

---

test/gst-vaapi/encode/10bit/hevc.py

add vme "low delay b" implementation for hevc 10bit
yuv420 cqp/cbr/vbr encode for gst-vaapi testing

gst-vaapi: add hevc-10 vme lowdelayb implementation

---

test/ffmpeg-qsv/encode/10bit/vp9.py

enable vp9 10bit encoding(vdenc) test for ffmpeg-qsv.

vp9_lp enc:enable vp9_lp 10bit vdenc for ffmpeg-qsv

---

.slashrc
lib/caps/APL/info
lib/caps/BSW/info
lib/caps/CFL/info
lib/caps/CML/info
lib/caps/EHL/info
lib/caps/GLK/info
lib/caps/ICL/info
lib/caps/KBL/info
lib/caps/SKL/info
lib/caps/TGL/info
lib/caps/WHL/info
lib/platform.py

Sometimes, references need to be stored in the baseline on a per-platform or per-gpu gen basis.  This adds support for using `"platform"` and/or `"gpu.gen"` keys in the `refctx` user config variable for each test case definition.  The `"platform"` key is expanded at run-time to the platform specified in the `--platform` command-line option.  The `"gpu.gen"` key is expanded at run-time to the gpu gen specified in the `lib/caps/{platform}/info` file.
Some examples (note: `"driver"` key is previously supported):
```python
refctx = ["driver", "gpu.gen"]
refctx = ["drv.{driver}", "gpu.gen.{gpu[gen]}"]
refctx = ["driver", "platform"]
refctx = ["drv.{driver}", "plat.{platform}"]
refctx = ["drv[{driver}].gpu[{gpu[gen]}]"]
```
In the last example, the baseline entry for each test case would look …

Support for platform and gpu.gen in refctx

---

test/ffmpeg-qsv/decode/decoder.py
test/ffmpeg-vaapi/decode/decoder.py

The autoscale option is added in ffmpeg commit 0b511bd9a548.
For multi resolution clips, we don't want to scale the raw
decoded output since scaling algorithms can produce different
results between various drivers/middleware.  For most codecs,
the decoded result should be the same across different
driver/middleware implementations.  This decoded result can
only be effectively validated and compared when scaling is
disabled.  This also allows us to share a single baseline
reference across all tested drivers/middleware.

test/ffmpeg: disable autoscale for decode tests

---

test/ffmpeg-qsv/util.py

added Y412 format map in ffmpeg-qsv to enable 12bit
444 decode

vaapi-fits: added Y412 format map in ffmpeg-qsv

---

test/gst-msdk/encode/encoder.py

The low-power property type changed in upstream for
hevc plugin:
https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/merge_requests/1405
Thus, adjust accordingly.

gst-msdk: fix hevc low-power type changed

---

.slashrc

The user config may want to set the refctx based
on some command-line option.  However, the command-line
is not parsed until after the user config is loaded.
Thus, allow a function/lambda in refctx so the user
config can delay evaluation until the refctx is expanded
during test runtime.
For example, user config may want to use the platform
command-line value to determine an appropriate refctx.
But, media._get_platform_name() is not resolved until
after the user config is loaded.  Thus, the user config
can delay the evaluation based on platform when the
refctx is expanded during test runtime like so:
```python
refctx = [
"driver",
lambda: "gpu.gen" if media._get_platform_name() in ["XYZ"] else None
]
```
...this will produce ["driver", "gpu.gen"] only when the
platform name is "XYZ". …

plugin: support function/lambda in refctx

---

test/gst-msdk/encode/encoder.py

AYUV input was enabled for all codecs in:
commit b56ee2407a0163e57d5174c3d60b3124aa37188b
Author: Luo Focus <focus.luo@intel.com>
Date:   Fri Jul 10 01:52:28 2020 +0000
fixed the ayuv support issue for gst-msdk
...however, only hevc-8 currently supports AYUV input
through and through.
AYUV input should not be enabled for other codecs.
More specifically, msdkmjpegenc element does not
currently support AYUV/VUYA srcpad format.

gst-msdk/encode: only enable AYUV for hevc-8

---

test/gst-vaapi/util.py

added gst-vaapi profile map for hevc 8bit vdenc
444 encode

hevc-8 lp 444: added gst-vaapi profile map

---

lib/formats.py
lib/framereader.py
lib/metrics.py
test/self/formats.py

https://en.wikipedia.org/wiki/Peak_signal-to-noise_ratio#Definition
PSNR and SSIM should be calculated using the correct max possible
pixel value for each bit depth.  For 8 bit, the skimage uses the
correct default of 255.  But for 10 bit and 12 bit, we read the
pixels into 16/32 bit dtype, and skimage will set the default for
those to the max possible value that the "data type" can handle.
However, the max pixel value is less for 10/12 bit formats. It
should be (2^B)-1.  Thus, specify the data_range param to skimage
PSNR and SSIM so that the correct max possible pixel value is used
in the calculation.
Also, the 10/12 bit frame readers must mask or shift away any
insignificant bits (depending on format) so that the pixel value
starts at the lsb and puts it into the correct pixel value …

metrics: Use max possible pixel value for PSNR and SSIM

---

test/gst-msdk/util.py

added main444-10 to main-444-10 map for gst-msdk
for hevc 10bit 444 encode

gst-msdk: added main444-10 to main-444-10 map

---

tools/bdrate

tools: add bdrate script
This script calculates bdrate of test results between
two results.xml files (specified as command line options).
For cqp cases, the 'qp' param is the variant.  For other cases
(e.g. vbr, cbr), the 'bitrate' param is the variant.
The script depends on the bd-metric python module:
sudo pip3 install bd-metric
cc: @zhangyuankun-star @xuguangxin @FocusLuo

bdrate tool

---

lib/caps/RKL/iHD
lib/caps/TGL/iHD
test/gst-msdk/decode/12bit/vp9.py
test/gst-msdk/util.py

1, vp9 12bit decode support in lib/caps for TGL/RKL firstly
2, vp9 12bit gst-msdk decode enabling

gst-msdk decode added vp9 12bit 420 support

---

test/ffmpeg-qsv/decode/decoder.py
test/ffmpeg-qsv/encode/encoder.py

ffmpeg-qsv: use '-hwaccel_output_format qsv' for decode

---

.slashrc

older detect is catch for the 'Resetting' + 'hang' keyword in dmesg,
with current kernel behavior, now just catch GPU hang keyword
Signed-off-by: Bin Wu <binx.wu@intel.com>

update .slashrc for detect the GPU hang

---

lib/gstreamer/msdk/decoder.py
lib/gstreamer/msdk/encoder.py
lib/gstreamer/msdk/transcoder.py
lib/gstreamer/msdk/vpp.py
lib/gstreamer/vaapi/decoder.py
lib/gstreamer/vaapi/encoder.py
lib/gstreamer/vaapi/transcoder.py
lib/gstreamer/vaapi/vpp.py

Since gst-plugins-base@660b5e4a the chroma-site is
no longer assumed by the base decoder.  This changed
the chroma resampling chosen by videoconvert in many
cases because gst-vaapi and gst-msdk decoders no longer
provide chroma-site setting on their src caps.
Thus, disable chroma resampling on videoconvert to
workaround the issues reported here:
https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi/-/issues/284
https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/issues/1456

lib/gstreamer: use chroma-mode=none for videoconvert

---

lib/ffmpeg/vaapi/util.py

ffmpeg-vaapi hevc-12bit 422 decode support

Added ffmpeg-vaapi hevc-12 422 support

---

lib/caps/DG1/iHD
lib/caps/ICL/iHD
lib/caps/RKL/iHD
lib/caps/TGL/iHD
lib/ffmpeg/qsv/encoder.py
lib/ffmpeg/qsv/transcoder.py
lib/ffmpeg/vaapi/encoder.py
lib/ffmpeg/vaapi/transcoder.py
lib/gstreamer/msdk/transcoder.py
lib/gstreamer/vaapi/encoder.py
lib/gstreamer/vaapi/transcoder.py
lib/parameters.py
test/ffmpeg-qsv/encode/hevc.py
test/ffmpeg-vaapi/encode/10bit/hevc.py
test/ffmpeg-vaapi/encode/hevc.py
test/gst-msdk/encode/hevc.py
test/gst-vaapi/encode/10bit/hevc.py
test/gst-vaapi/encode/hevc.py

HEVCe LDB is/will be the default for all
vaapi/msdk plugins.
NOTE: HEVCe LDB for ffmpeg-vaapi is only in cartwheel
at the moment.  It doesn't select LDB by default
yet, but a patch will be submitted to enable it as
the default soon.

Remove low delay B specializations

---

lib/caps/RKL/iHD
lib/caps/TGL/iHD
lib/ffmpeg/vaapi/util.py

ffmpeg-vaapi added vp9-12bit 444 decode support

ffmpeg-vaapi added vp9-12bit 444 decode support

---

lib/__init__.py
lib/caps/DG1/iHD
lib/caps/RKL/iHD
lib/caps/TGL/iHD
lib/ffmpeg/qsv/decoder.py
lib/ffmpeg/vaapi/decoder.py
lib/gstreamer/msdk/decoder.py
lib/gstreamer/vaapi/decoder.py
lib/util.py

lib: support test skip for missing features in decoders
Some test cases require extra codec features based on platform
capabilities.
This adds support to decoders to allow test config and
platform caps to match arbitrary features required for the
test case to run.  If no match, then the test case can be
skipped.
For example, in the test case specification the user can define
"features = ['xyz', 'abc']" to enable the case on platforms
that only have 'xyz' and 'abc' features defined in the
platform capabilities file (i.e. in lib/caps/..).
To declare a set of supported/unsupported codec features in the
platform caps, we can define for example:
"features = dict(xyz = True, abc = True, other = False)"
...where True means the feature is supported and False means
the feature is unsupported.  A …

Support test skip for missing features in decoder caps (and define SCC feature)

---

.travis.yml
lib/ffmpeg/vaapi/transcoder.py

The gpu gen is only known during "run" command.  Thus, move
LDB workaround to test runtime so we don't break other
commands.

ffmpeg/vaapi: fix "list" command error caused by WA

---

test/gst-msdk/decode/av1.py
test/gst-vaapi/decode/av1.py

gst-vaapi/msdk add .av1 file extension support
high resolution av1 decode will include .av1 file extension

gst-vaapi/msdk add .av1 file extension support

---

lib/gstreamer/msdk/decoder.py
lib/gstreamer/msdk/encoder.py
lib/gstreamer/msdk/transcoder.py
lib/gstreamer/msdk/vpp.py
lib/gstreamer/vaapi/decoder.py
lib/gstreamer/vaapi/encoder.py
lib/gstreamer/vaapi/transcoder.py
lib/gstreamer/vaapi/vpp.py

Depends on https://github.com/intel-media-ci/gst-checksumsink/pull/1
This allows us to force pipelines to stop processing more
frames when the input stream contains more frames than requested
by the test case.

gst: use eos-after in checksumsink2

---

lib/caps/RKL/iHD
lib/caps/TGL/iHD

Only TGL and TGL relative refresh platforms (Such as TGL/RKL and ADL) support vp8 dec features.
Based on iHD side, google requires the VP8 dec feature support, so iHD add vp8 dec feature back on TGL relative platforms.

Caps: add vp8 dec support define on TGL and TGL relative platforms

---

lib/ffmpeg/vaapi/decoder.py

Interestingly, I'm seeing the "unsupported HW accel" in test
case logs on platforms that we expect to do HW AV1d.  This
debug message indicates that we are not getting HW accelerated
AV1d path and that ffmpeg just falls back to SW decode and
succeeds.
Thus, don't allow the test case to pass if HW accel AV1d
can't be achieved!

ffmpeg-vaapi: detect unsupported AV1d HW accel

---

lib/ffmpeg/vaapi/decoder.py

Reverts intel/vaapi-fits#279
See discussion in #279 why the message does not mean hw accel failure.

Revert "ffmpeg-vaapi: detect unsupported AV1d HW accel"

---

test/gst-msdk/decode/10bit/av1.py
test/gst-msdk/decode/av1.py
test/gst-vaapi/decode/10bit/av1.py
test/gst-vaapi/decode/av1.py

ivfparse is actually a demuxer, and av1parse is required after ivfparse.

Update the command  for av1 decoding.

---

lib/caps/ADL/iHD
lib/caps/DG1/iHD
lib/caps/RKL/iHD
lib/caps/SG1/iHD
lib/caps/TGL/iHD

Gen12 platforms added hevc main still dec feature support

Caps: Gen12 platforms added main still dec feature

---

lib/caps/ADL/iHD
lib/caps/RKL/iHD

For Gen12: the latest iHD only support vp8 dec
on TGL platform
https://github.com/intel/media-driver

Caps: VP8 dec only support on TGL of Gen12

---

test/ffmpeg-qsv/encode/10bit/hevc.py
test/ffmpeg-qsv/encode/10bit/vp9.py
test/ffmpeg-qsv/encode/avc.py
test/ffmpeg-qsv/encode/hevc.py
test/ffmpeg-qsv/encode/jpeg.py
test/ffmpeg-qsv/encode/mpeg2.py
test/ffmpeg-qsv/encode/vp9.py
test/ffmpeg-vaapi/encode/10bit/hevc.py
test/ffmpeg-vaapi/encode/10bit/vp9.py
test/ffmpeg-vaapi/encode/avc.py
test/ffmpeg-vaapi/encode/hevc.py
test/ffmpeg-vaapi/encode/jpeg.py
test/ffmpeg-vaapi/encode/mpeg2.py
test/ffmpeg-vaapi/encode/vp8.py
test/ffmpeg-vaapi/encode/vp9.py
test/gst-msdk/encode/10bit/hevc.py
test/gst-msdk/encode/10bit/vp9.py
test/gst-msdk/encode/avc.py
test/gst-msdk/encode/hevc.py
test/gst-msdk/encode/jpeg.py
test/gst-msdk/encode/mpeg2.py
test/gst-msdk/encode/vp9.py
test/gst-vaapi/encode/10bit/hevc.py
test/gst-vaapi/encode/10bit/vp9.py
test/gst-vaapi/encode/avc.py
test/gst-vaapi/encode/hevc.py
test/gst-vaapi/encode/jpeg.py
test/gst-vaapi/encode/mpeg2.py
test/gst-vaapi/encode/vp8.py
test/gst-vaapi/encode/vp9.py

This change moves common slash.requires to the class
level on derived test classes to remove the duplication
that previously occurred across each class test method.
The class-level slash.requires on subclasses are supported
since slash 1.7.10.

test/encode: move requires to class level

---

lib/gstreamer/decoderbase.py
lib/gstreamer/encoderbase.py
lib/gstreamer/msdk/decoder.py
lib/gstreamer/msdk/encoder.py
lib/gstreamer/msdk/util.py
lib/gstreamer/msdk/vpp.py
lib/gstreamer/util.py
lib/gstreamer/vaapi/decoder.py
lib/gstreamer/vaapi/encoder.py
lib/gstreamer/vaapi/util.py
lib/gstreamer/vaapi/vpp.py
lib/gstreamer/vppbase.py

This is a minimal refactor to consolidate common gstreamer decoder, encoder and vpp test code into base classes so they can be shared between vaapi and msdk (and va) plugin tests without slash.requires and other plugin specific settings leaking across subclasses (e.g. see https://github.com/intel/vaapi-fits/pull/284#pullrequestreview-653824960).  NOTE: this does not include transcoder consolidation (will submit in separate PR).

gstreamer: common base classes

---

lib/gstreamer/msdk/util.py

Add hevc-8 mainsp profile map for gst-msdk

Add hevc-8 mainsp profile map for gst-msdk

---

lib/common.py
test/ffmpeg-qsv/encode/10bit/vp9.py
test/ffmpeg-qsv/encode/vp9.py
test/ffmpeg-vaapi/encode/10bit/hevc.py
test/ffmpeg-vaapi/encode/10bit/vp9.py
test/ffmpeg-vaapi/encode/hevc.py
test/ffmpeg-vaapi/encode/mpeg2.py
test/ffmpeg-vaapi/encode/vp8.py
test/ffmpeg-vaapi/encode/vp9.py
test/gst-msdk/encode/10bit/vp9.py
test/gst-msdk/encode/vp9.py
test/gst-vaapi/encode/10bit/vp9.py
test/gst-vaapi/encode/vp9.py

Test function parameters need to be consistent across each
middleware implemented test.  However, some test functions
don't support some parameters due to middleware limitations.
Thus, if a test is variated on the unused parameter(s) it
creates a redundancy of the same test case.
This change adds support to allow test cases to be skipped
when unused parameter(s) create a redundancy where the used
parameters have already been exercised by another case.

skip redundant cases with unused params

---

lib/ffmpeg/qsv/util.py
lib/ffmpeg/vaapi/util.py
lib/gstreamer/msdk/util.py
lib/gstreamer/va/util.py
lib/gstreamer/vaapi/util.py
lib/util.py

Currently, user config cases can be added on a component-specific
basis.  Often, this mechanism is used to avoid running cases on a
specific component.  That is, if the user config wants cases to be
run on all components except component X, then the user config has
to know about all of the components.  This poses a problem where
the user config might forget about one component where the intention
is to run it.  Or, if a new component is added to the framework,
then all user configs need to be updated to ensure cases are added
to that new component.
This change adds a test case property, called "not_components",
that allows the user config to explicitly avoid specific
components for given cases.  Thus, the user config does not
need to know about every available/new component in the …

load_test_spec: allow cases to explicitly avoid components

---

lib/caps/ADL/info
lib/common.py
lib/mfx/__init__.py
lib/mfx/runtime.py
requirements.txt
test/ffmpeg-qsv/general/__init__.py
test/ffmpeg-qsv/general/runtime.py
test/gst-msdk/general/__init__.py
test/gst-msdk/general/runtime.py

These are crude tests that execute ffmpeg-qsv and gst-msdk pipelines and searches which MFX dispatcher and runtime libraries are loaded in the process' memory map.

Add tests to detect and check MFX runtime.

---

lib/caps/ADL/iHD
lib/caps/DG1/iHD
lib/caps/RKL/iHD
lib/caps/SG1/iHD
lib/caps/TGL/iHD
lib/formats.py
lib/framereader.py
lib/gstreamer/msdk/util.py
lib/metrics.py

1, caps define support in Gen12
2, enabled vaapi-fits core support for BGRX
3, enabled gst-msdk format map

added format BGRX support and enabled the gst-msdk path

---

lib/caps/GLK/iHD

Caps: removed vp8 encode on iHD GLK

---

test/gst-va/decode/10bit/av1.py

fixed a typo for av1-10 dec cmd line, which miss type
"vaapiav1dec" as "vaav1dec"
On local machine, the "vaapiav1dec" worked with cmdline
./smoke run test/gst-va/decode/10bit/av1.py --pl TGL
\ --contex=sanity

gst-va: fixed a typo for av1-10 dec cmd line

---

lib/gstreamer/vaapi/transcoder.py

This Change avoid load libav library
openh264dec need openh264 from gst-plugins-bad
libde265dec need libde265 from gst-plugin-bad
mpeg2dec need libmpeg2 from gst-plugin-ugly

Change gst-vaapi transcode software decode plugin

---

lib/gstreamer/msdk/transcoder.py

This Change avoid load libav library
openh264dec need openh264 from gst-plugins-bad
libde265dec need libde265 from gst-plugin-bad
mpeg2dec need libmpeg2 from gst-plugin-ugly

Change gst-msdk transcode software decode plugin

---

lib/ffmpeg/qsv/vpp.py
test/ffmpeg-qsv/vpp/composite.py

Closes #173 
overlay_qsv fails P010 cases.  It shouldn't.  But let it fail anyway to expose the gap.

Add ffmpeg-qsv (overlay_qsv) VPP composite test

---

lib/ffmpeg/qsv/encoder.py
lib/parameters.py
test/ffmpeg-qsv/encode/avc.py

Add avc forced_idr encode test support for ffmpeg-qsv
Signed-off-by: Xu Yefeng <yefengx.xu@intel.com>

ffmpeg-qsv: add avc forced_idr encode test support

---

lib/ffmpeg/vaapi/vpp.py
test/ffmpeg-vaapi/vpp/composite.py

overlay_vaapi supported on cartwheel.  vaapi-fits example case passed and internal bat/sanity cases passed on KBL.

ffmpeg-vaapi: add vpp composite test

---

lib/ffmpeg/qsv/encoder.py
test/ffmpeg-qsv/encode/avc.py

For forced_idr, don't use the same name for the test
variable as the user config variant key.  Because
tests that don't explicitly use the forced_idr test
variable (e.g. vbr, cbr, etc.) will inherit the config
variant as the test variable value.
Thus, rename the test variable to vforced_idr to avoid
conflict with user config.
Since #316
cc: @yefengxx @FocusLuo @Bin-CI

ffmpeg-qsv: fix forced_idr bug

---

lib/ffmpeg/qsv/encoder.py
lib/ffmpeg/vaapi/encoder.py
lib/gstreamer/encoderbase.py

Add encode test support for user config test case "call_timeout" override.

encoder: support config call_timeout

---

config/avc.default
config/hevc.default
config/jpeg.default
config/mpeg2.default
config/vp8.default
config/vp9.default
lib/parameters.py

Encode test params should be wrapped inside their
own dict to prevent accidental class variable
conflicts as found in #323.

lib: parse encode config params from variants dict

---

lib/ffmpeg/qsv/decoder.py
lib/ffmpeg/qsv/encoder.py
lib/ffmpeg/qsv/transcoder.py
lib/ffmpeg/qsv/vpp.py
test/ffmpeg-qsv/general/runtime.py

The latest FFmpeg supports hw_device_ctx interface for QSV decoder, we
may use the common device stuff to initialize hw device for QSV
decoder. In addtion, -filter_hw_device option is not needed when there
is only one hw device.

Simplify command line for QSV

---

lib/ffmpeg/encoderbase.py
lib/ffmpeg/qsv/util.py
lib/parameters.py
test/ffmpeg-qsv/encode/av1.py

1,  added av1-8 enc: added parameters and variants in core
2, ffmpeg-qsv lib added new parameter tile_cols and tile_rows
3, added av1 8bit map
4, ffmpeg-qsv added new av1 enc implement support

ffmpeg-qsv av1 8bit encode support low power cqp mode

---

lib/gstreamer/decoderbase.py
lib/gstreamer/encoderbase.py
lib/gstreamer/msdk/decoder.py
lib/gstreamer/msdk/encoder.py
lib/gstreamer/va/decoder.py
lib/gstreamer/vaapi/decoder.py
lib/gstreamer/vaapi/encoder.py
lib/properties.py
test/gst-msdk/encode/mpeg2.py
test/gst-vaapi/encode/mpeg2.py

Move gstreamer decode/encode command-line generator code into separate classes so they can be reused across different test contexts.

lib/gst: decouple encode/decode command-line from test classes

---

lib/gstreamer/encoderbase.py
lib/gstreamer/msdk/encoder.py
lib/gstreamer/msdk/transcoder.py
lib/gstreamer/vaapi/encoder.py
lib/gstreamer/vaapi/transcoder.py

1. The gstreamer msdk elements deprecated the `low-power` property in favor of the `tune` property.
1. AVCe LP only supports CQP rate-control on some older platforms.  Thus, use CQP for AVC LP transcode tests.

gstreamer/encode: use tune property and cqp for avc lp transcode

---

lib/ffmpeg/qsv/transcoder.py
lib/ffmpeg/vaapi/transcoder.py

Some older platforms only support AVCe cqp in
low power (vdenc) mode.  Thus, explicitly use
cqp rate control for avc lp transcode.

ffmpeg/transcode: use cqp in lp mode

---

.slashrc
lib/platform.py

With Windows side support, some code maybe different between windows/linux
Because they use the different environment, some option/environment will different
Like:
windows side don't restrict the render device

slashrc: add os type detect

---

lib/ffmpeg/decoderbase.py

The hwformat can be specified in the -hwaccel_output_format
option directly and removes the need for using a hwdownload
filter.
This also makes it easier to use other hwaccel plugins where
the hwaccel format name is not the same as the plugin name.
For example, d3d11va is an hwaccel plugin name but the
corresponding hwaccel format name is d3d11... so would require
additional class property to handle it in previous command
template.  Now setting hwformat in hwaccel_output_format
directly, we don't need to do any special case here.

lib/ffmpeg/decoderbase: remove hwdownload filter

---

.slashrc
lib/caps/TGL/d3d11
lib/common.py
lib/ffmpeg/d3d11/__init__.py
lib/ffmpeg/d3d11/decoder.py
lib/ffmpeg/d3d11/util.py
lib/ffmpeg/decoderbase.py
lib/ffmpeg/util.py
lib/platform.py
test/ffmpeg-d3d11/__init__.py
test/ffmpeg-d3d11/decode/10bit/__init__.py
test/ffmpeg-d3d11/decode/10bit/av1.py
test/ffmpeg-d3d11/decode/10bit/hevc.py
test/ffmpeg-d3d11/decode/10bit/vp9.py
test/ffmpeg-d3d11/decode/__init__.py
test/ffmpeg-d3d11/decode/avc.py
test/ffmpeg-d3d11/decode/hevc.py
test/ffmpeg-d3d11/decode/jpeg.py
test/ffmpeg-d3d11/decode/mpeg2.py
test/ffmpeg-d3d11/decode/vc1.py
test/ffmpeg-d3d11/decode/vp8.py
test/ffmpeg-d3d11/decode/vp9.py

This PR adds additional patches to #342 and test implementations for ffmpeg-d3d11.
Example:
```
export LIBVA_DRIVER_NAME=d3d11
./vaapi-fits run test/ffmpeg-d3d11 --platform TGL \
--parallel-metrics --device d3d11va -vv
```
Obviously, d3d11 is not a vaapi driver... and using
LIBVA_DRIVER_NAME to set this is awkward.  So we will
want to improve upon this at some point.

WSL updates for #342

---

lib/ffmpeg/d3d11/decoder.py
lib/ffmpeg/qsv/decoder.py
lib/ffmpeg/qsv/encoder.py
lib/ffmpeg/qsv/transcoder.py
lib/ffmpeg/qsv/vpp.py
lib/ffmpeg/util.py
lib/ffmpeg/vaapi/decoder.py
lib/ffmpeg/vaapi/encoder.py
lib/ffmpeg/vaapi/transcoder.py
lib/ffmpeg/vaapi/vpp.py
test/ffmpeg-qsv/general/runtime.py

When have_ffmpeg_hwaccel is false we should return
a context, too, so slash.requires reports something
useful.
Without the context, the missing requirement will emit:
Skipped (Unmet requirement: ?)
With a context, it will emit (for example):
Skipped (Unmet requirement: d3d11va)

lib/ffmpeg: provide context for have_ffmpeg_hwaccel

---

lib/ffmpeg/qsv/util.py

ffmpeg-qsv can load d3d11/iHD on windows side

lib/ffmpeg/qsv/util.py: add d3d11 support for ffmpeg-qsv test

---

lib/ffmpeg/encoderbase.py
lib/parameters.py
test/ffmpeg-qsv/encode/hevc.py

Add hevc forced_idr encode test support for ffmpeg-qsv
Signed-off-by: Xu Yefeng <yefengx.xu@intel.com>

ffmpeg-qsv: add hevc forced_idr encode test support

---

lib/caps/TGL/d3d11

The added cases are all supported by ffmpeg-libvpl on Windows,
so add them all for testing.

lib/caps/TGL/d3d11: add supported cases for libvpl

---

lib/caps/TGL/dxva2
lib/ffmpeg/dxva2/__init__.py
lib/ffmpeg/dxva2/decoder.py
lib/ffmpeg/dxva2/util.py
test/ffmpeg-dxva2/__init__.py
test/ffmpeg-dxva2/decode/10bit/__init__.py
test/ffmpeg-dxva2/decode/10bit/av1.py
test/ffmpeg-dxva2/decode/10bit/hevc.py
test/ffmpeg-dxva2/decode/10bit/vp9.py
test/ffmpeg-dxva2/decode/__init__.py
test/ffmpeg-dxva2/decode/avc.py
test/ffmpeg-dxva2/decode/hevc.py
test/ffmpeg-dxva2/decode/jpeg.py
test/ffmpeg-dxva2/decode/mpeg2.py
test/ffmpeg-dxva2/decode/vc1.py
test/ffmpeg-dxva2/decode/vp8.py
test/ffmpeg-dxva2/decode/vp9.py

fork from ffmpeg-d3d11
1. add caps of TGL/dxva2
2. add lib/ffmpeg/dxva2
3. add test/ffmpeg-dxva2

Add dxva2 support for ffmpeg

---

lib/caps/RKL/d3d11
lib/caps/RKL/dxva2
lib/caps/TGL/d3d11
lib/caps/TGL/dxva2

fork d3d11 and dxva2 from TGL to support RKL test platform

lib/caps/RKL fork d3d11 and dxva2 from TGL

---

lib/ffmpeg/qsv/encoder.py
lib/ffmpeg/qsv/util.py

Currently, only cartwheel ffmpeg-qsv + onevpl supports
HEVC main10sp encode.
Thus, skip test if -main10sp is not found in the ffmpeg
encoder options.

ffmpeg/qsv: skip test if no main10sp option

---

test/ffmpeg-d3d11/decode/av1.py

add av1.py to enable 8bit av1 test cases

ffmpeg-d3d11: add av1.py for ffmpeg-d3d11

---

lib/gstreamer/vaapi/encoder.py

gst-vaapi encoders can support custom VBR
minrate with target-percentage property.
Thus, set target-percentage property based on
minrate/maxrate to allow future tests to tweek
the target.
Currently, gst-vaapi tests hardcode minrate/maxrate
at 70% which is the gst-vaapi encoder default.  Thus,
this change should not affect current test case
results.

lib/gst/vaapi/encoder: handle minrate

---

lib/mixin/vpp.py
test/ffmpeg-qsv/vpp/sharpen.py

Change metric threshold from 0.2 to 0.25 in test/ffmpeg-qsv/vpp/sharpen.

vpp/sharpen: change metric threshold to 0.25

---

lib/baseline.py

Allow PSNR drop tolerance within 98% of reference value.
This relaxes the pass/fail criteria, instead of a constant
0.2db drop tolerance.  For example, a 40db reference allows
for 0.8db drop tolerance, now.

baseline: use 98% psnr drop tolerance

---

lib/ffmpeg/vaapi/encoder.py
test/ffmpeg-vaapi/encode/10bit/hevc.py
test/ffmpeg-vaapi/encode/10bit/vp9.py
test/ffmpeg-vaapi/encode/hevc.py
test/ffmpeg-vaapi/encode/mpeg2.py
test/ffmpeg-vaapi/encode/vp8.py
test/ffmpeg-vaapi/encode/vp9.py

The base vaapi encoder in ffmpeg uses the global
-compression_level option to set the libva buffer
quality level parameter.
Only the vaapi h264 encoder in ffmpeg supports
the global -quality option to set the libva buffer
quality level parameter.  However, since the h264
encoder derives from the base vaapi encoder, it also
supports the -compression_level option.  Thus, -quality
is redundant in h264 encoder.
Using -compression_level allows us to properly enable
the "quality" test parameter usage in the other encoder
tests (e.g. hevc, vp9...).

ffmpeg-vaapi encode: use compression_level option for quality (tu)

---

lib/caps/TGL/dxva2

D3D9 does not support av1 decode, so remove them from ci test.

caps: remove av1 test from dxva2 config

---

lib/caps/RKL/d3d11
lib/caps/RKL/dxva2

According to driver team, the U and V can be changed for TGL Windows.

caps: Change RKL chroma config for d3d11 and dxva2

---

lib/caps/RKL/dxva2

D3D9 does not support av1 decode, so remove them from ci test.

caps: remove av1 test from dxva2 config on RKL

---

.slashrc

Load media._get_gpu_gen() on VAAPI_FITS_CONFIG_FILE will failed
Because load configure before media plugin enable
So paser the parameter before load VAAPI_FITS_CONFIG_FILE
then can base on media._get_gpu_gen to direct skip test case

.slashrc: parser parameter before load configure file

---

lib/gstreamer/msdk/vpp.py

Align the gst-msdk cmd arguments with ffmpeg-qsv.

lib/gstreamer/msdk/vpp:remove scaling-mode parameter

---

lib/mfx/runtime.py

this patch to help trace general/runtime failed reason

lib/mfx/runtime: add logger info to record runtime path

---

.slashrc

Reverts intel/vaapi-fits#382
This is bad.  It breaks all sorts of slash framework logic (e.g. vaapi-fits list).  The only way to access media._get_gpu_gen() at config level is to use various supported runtime evaluated lambdas.

Revert ".slashrc: parser parameter before load configure file"

---

test/gst-msdk/encode/av1.py

Add av1parse in cmd can fix the issue in gst-msdk/encode/av1 on DG2.

test/gst-msdk/encode/av1: add av1parse

---

lib/ffmpeg/decoderbase.py
lib/ffmpeg/encoderbase.py
lib/ffmpeg/qsv/vpp.py
lib/ffmpeg/vaapi/vpp.py
lib/gstreamer/decoderbase.py
lib/gstreamer/encoderbase.py
lib/gstreamer/vppbase.py

The post_validate hook can be defined in user config test
case parameters.  This allows user config to do additional
runtime processing on each test case before the test starts
executing command lines.  For example, the post_validate
hook could instruct the case to skip based on various
criteria that can only be evaluated during test runtime
like gpu gen, platform name, etc...

Add post_validate hook to decode/encode/vpp tests

---

test/gst-msdk/encode/av1.py

Class cbr_lp missing bframes. 

test/gst-msdk/encode/av1: add bframes in cbr_lp

---

lib/ffmpeg/encoderbase.py
lib/ffmpeg/qsv/encoder.py
test/ffmpeg-qsv/encode/hevc.py

1. Fix default profiles in hevce
2. Validate/check for intra refresh command output messages
3. Ensure intref params are reflected in the name to minimize duplicate with other test case artifact names.

Some fixups for intra refresh tests

---

lib/platform.py

distro.linux_distribution is deprecated from python3.8
now replace this function

lib/platform: replace distro.linux_distribution

---

lib/gstreamer/va/encoder.py
test/gst-va/encode/avc.py

The gst-va lowpower encode cases were not actually doing
lowpower encode!
Properly setup gst-va lp tests to ensure we are calling
the lpenc variant of the encoder elements.

gst-va: fix lowpower encode tests

---

lib/ffmpeg/encoderbase.py
lib/gstreamer/encoderbase.py
lib/gstreamer/msdk/encoder.py
lib/parameters.py
test/ffmpeg-qsv/encode/avc.py
test/ffmpeg-qsv/encode/hevc.py
test/gst-msdk/encode/avc.py
test/gst-msdk/encode/hevc.py

lib/parameters: added functions for max_frame_size
ffmpeg-qsv: added max_frame_size for avc/hevc enc
gst-msdk: added max_frame_size for avc/hevc enc
Signed-off-by: Xu Yefeng <yefengx.xu@intel.com>

ffmpeg-qsv/gst-msdk: enable max frame size test

---

lib/ffmpeg/encoderbase.py

Should use f-string for local variable

lib/ffmpeg/encoderbase: fix bug in forced_idr

---

lib/ffmpeg/d3d11/decoder.py
lib/ffmpeg/decoderbase.py
lib/ffmpeg/dxva2/decoder.py
lib/ffmpeg/encoderbase.py
lib/ffmpeg/qsv/decoder.py
lib/ffmpeg/qsv/encoder.py
lib/ffmpeg/vaapi/decoder.py
lib/ffmpeg/vaapi/encoder.py
test/ffmpeg-qsv/encode/mpeg2.py
test/ffmpeg-vaapi/encode/mpeg2.py

The encode/decode command line generator code is split into their own classes.  This allows them to be reused easier in different contexts/tests.  It also allows for simpler override for various properties based on plugin component differences.
cc: @wenbinc-Bin

lib/ffmpeg: decouple encoder/decoder from test class

---

lib/ffmpeg/encoderbase.py
lib/ffmpeg/vaapi/encoder.py

The -rc_mode command-line option is only valid for
vaapi encode plugins in ffmpeg.
Since...
commit b663377584320edf0dd19e6bdd86afee0f8c6090
Author: U. Artie Eoff <ullysses.a.eoff@intel.com>
Date:   Tue Jul 12 14:50:29 2022 -0400
lib/ffmpeg: decouple encoder command-line from test class
...the rc_mode option was being added to all ffmpeg plugin
command-lines in ffmpeg/encoderbase.py.
On Linux, invalid options only generate warnings which ffmpeg
will ignore and gracefully proceed.  However, on Windows,
invalid options are treated as errors and ffmpeg aborts.
This fixes it so that the -rc_mode option is only applied
to the ffmpeg/vaapi/encoder.py specialization.
VIZ-17445

ffmpeg/encode: move rc_mode option to vaapi only

---

lib/caps/ADL/iHD
lib/caps/DG1/iHD
lib/caps/RKL/iHD
lib/caps/SG1/iHD
lib/caps/TGL/iHD

1. According to media-driver wiki, vpp/sharpen/yv12 input/output format does not support on >= gen12 platform. Remove vpp/sharpen/yv12 output format on >= gen12 platform
2. Remove vpp/sharpen/I420 input/output format on >= gen12 platform

Remove vpp/sharpen/yv12 on >= gen12 platform

---

lib/ffmpeg/encoderbase.py
lib/ffmpeg/qsv/encoder.py
lib/ffmpeg/vaapi/encoder.py
test/ffmpeg-qsv/encode/av1.py
test/ffmpeg-vaapi/encode/av1.py

1. Add bframes in ffmpeg/encode/av1 cbr_lp 
2. Set tile parameters respectively on ffmpeg-qsv/vaapi

Set tile parameters respectively on ffmpeg-qsv/vaapi

---

lib/ffmpeg/qsv/encoder.py

lookahead does not report rcmode in usual manner

lib/ffmpeg/qsv: fix rcmode check when using ladepth

---

lib/ffmpeg/encoderbase.py
lib/parameters.py
test/ffmpeg-qsv/encode/10bit/hevc.py
test/ffmpeg-qsv/encode/avc.py
test/ffmpeg-qsv/encode/hevc.py
test/ffmpeg-vaapi/encode/10bit/hevc.py
test/ffmpeg-vaapi/encode/avc.py
test/ffmpeg-vaapi/encode/hevc.py

1. Add ROI cases for ffmpeg-qsv/vaapi encode avc/hevc.
2. ROI does not work on cqp, so I didn't add cqp test.

Add ROI cases for ffmpeg-qsv/vaapi encode

---

lib/ffmpeg/util.py
lib/framereader.py

Since:
https://github.com/intel-media-ci/cartwheel-ffmpeg/pull/170
https://github.com/FFmpeg/FFmpeg/commit/6ab8a9d375ca922b2a94cd7160a4e3c5abe6339c
0yuv is no longer provided.

lib/ffmpeg: map AYUV->vuya

---

lib/ffmpeg/encoderbase.py
lib/ffmpeg/qsv/encoder.py
lib/parameters.py
test/ffmpeg-qsv/encode/avc.py

Add max/min qp for I/P/B frame in ffmpeg-qsv/encode/avc.

Add Max/min qp for I/P/B in ffmpeg-qsv/encode/avc

---

.slashrc
lib/ffmpeg/decoderbase.py
lib/ffmpeg/encoderbase.py
lib/ffmpeg/vppbase.py
lib/gstreamer/decoderbase.py
lib/gstreamer/encoderbase.py
lib/gstreamer/vppbase.py

The "gen_name" functions are a maintenance headache... easy to forget to update when new properties are added and cause filenames to not be unique.
Thus, use the unique test id and a counter to generate test artifact filenames.  Remove all gen_name functions.

Factor out the "gen_name" functions

---

lib/ffmpeg/decoderbase.py
lib/ffmpeg/encoderbase.py
lib/ffmpeg/util.py

Writing raw data to file, then reading into internal metric function adds unnecessary runtime overhead.
Instead, we can have FFmpeg calculate the MD5,SSIM, or PSNR concurrently.

FFmpeg: use inline metrics

---

lib/ffmpeg/decoderbase.py
lib/ffmpeg/encoderbase.py

In addition to previous WA 46e1964c1e189fb, jpeg enc also needs this for proper inline metric calc.
So apply it unconditionally during decode when set.

ffmpeg: WA: force in/out range for jpeg enc and dec

---

lib/ffmpeg/decoderbase.py

When a file path is used in ffmpeg filter option, the drive letter separator on Windows, ":", needs to be escaped so the ffmpeg command can parse it correctly. Otherwise, it will be mistaken as a filter option
separator.

lib/ffmpeg: escape and quote ssim/psnr filename for Windows support

---

lib/ffmpeg/decoderbase.py

The explicit "-map 0:v" does not capture unlabeled complex filtergraph outputs.
Thus, remove the explicit mapping so that the unlabeled filtergraph output will be automatically linked to the first output stream (in this case, the tee sink).
This is the intended behavior of a complex filtergraph according to ffmpeg documentation.  It was just broken until:
http://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=0d821edb40d27848304a7354b1c64c2e30e00e7d
Also see https://trac.ffmpeg.org/ticket/9990 discussion.

ffmpeg/decode: do not use explicit map

---

test/ffmpeg-qsv/encode/10bit/hevc.py
test/ffmpeg-qsv/encode/avc.py
test/ffmpeg-qsv/encode/hevc.py

If you don't set this parameter, h264 encode will automatically set to 0 but h265 won't,so need to set to 0 manually. maxrate needs to be equal to bitrate, but if maxrate is set to bitrate on ffmpeg, CBR will be used, so set maxrate=bitrate * 1.01.
Signed-off-by: Wang Hangjie <hangjiex.wang@intel.com>

ffmepg-qsv:Update TCBRC maxrate and bframes

---

lib/ffmpeg/decoderbase.py
lib/ffmpeg/encoderbase.py
lib/ffmpeg/qsv/decoder.py
lib/ffmpeg/qsv/encoder.py
lib/ffmpeg/qsv/transcoder.py
lib/ffmpeg/qsv/vpp.py
lib/ffmpeg/transcoderbase.py
lib/ffmpeg/vaapi/vpp.py
lib/ffmpeg/vppbase.py
test/ffmpeg-qsv/general/runtime.py

QSV for the windows & linux standard init device format: 
`-init_hw_device qsv=qsv,child_device=xxx`
for the Windows the xxx is GPU order like 0,1
for the Linux the xxx is redner device like /dev/dri/renderD128
This value can recive by vaapi-fit `device` parameter
VAAPI/D3D11/DXVA2 still use init device format:
`-init_hw_device {self.hwaccel}=hw:{self.hwdevice}`

lib/ffmpeg: add hwinit_format for the base class

---

lib/ffmpeg/encoderbase.py
test/ffmpeg-qsv/encode/10bit/hevc.py
test/ffmpeg-qsv/encode/avc.py
test/ffmpeg-qsv/encode/hevc.py

When maxrate = bitrate * 1.01 is set, it will not work on hevc. maxrate = bitrate is required.
However, if ffmpeg is set to maxrate = bitrate, CBR will be called, so maxrate must not be set.
Let VPL runtime set maxrate to use VBR and maxrate=bitrate. Also modify the bitrate detection function.
Signed-off-by: Wang Hangjie <hangjiex.wang@intel.com>

ffmpeg-qsv:Delete avc/hevc/10bit.hevc maxrate = bitrate * 1.01

---

lib/caps/TGL/d3d11
lib/caps/TGL/dxva2

d3d does not have yv12 or i420 format. Remove them from input and output format lists.

caps: remove yv12 and i420 for Windows vpp

---

lib/caps/RKL/dxva2
lib/caps/TGL/dxva2

These filters are not supported by d3d9. Now remove them.

caps: remove rotation and transpose filter from dxva2 caps

---

lib/mixin/vpp.py

VPP scaling in xstack may produce slightly different results depending on platform and underlying scaling method used in middleware/driver.  Thus, MD5 may differ and change as driver optimizations are made.  Use SSIM, instead, to allow small differences.
See recent iHD commit that motivates this change:
https://github.com/intel/media-driver/commit/a9c2df7b01c2

vpp/stack: use SSIM metric for xstack cases

---

lib/ffmpeg/encoderbase.py
lib/gstreamer/encoderbase.py

Some user-defined cases may not have enough frames to effectively achieve the desired bitrate.
For such cases, this enables the user to add
skip_checks = ['bitrate_gap'] to the case definition.
This supersedes #486

encode: add option to skip bitrate gap check

---

lib/caps/ADL/iHD
lib/caps/DG1/iHD
lib/caps/SG1/iHD
lib/caps/TGL/iHD
lib/gstreamer/va/util.py
lib/gstreamer/vaapi/util.py
test/gst-msdk/encode/12bit/__init__.py
test/gst-msdk/encode/12bit/hevc.py
test/gst-va/encode/12bit/__init__.py
test/gst-va/encode/12bit/hevc.py
test/gst-vaapi/encode/12bit/__init__.py
test/gst-vaapi/encode/12bit/hevc.py

TGL, ADL, DG1, and SG1 support HEVC VME 12bit 4:2:0 and 4:2:2 encoding.
gst-va supports 4:2:0 and 4:2:2 12bit profiles.
gst-vaapi and gst-msdk only support 4:2:0 12bit profiles.

Add gstreamer HEVC VME 12bit 420 and 422 tests

---

lib/ffmpeg/qsv/util.py
lib/ffmpeg/vaapi/util.py
test/ffmpeg-qsv/encode/12bit/__init__.py
test/ffmpeg-qsv/encode/12bit/hevc.py
test/ffmpeg-vaapi/encode/12bit/__init__.py
test/ffmpeg-vaapi/encode/12bit/hevc.py

HEVCe VME 12bit 4:2:0 and 4:2:2 support

ffmpeg: add HEVCe VME 12bit tests

---

test/ffmpeg-vaapi/encode/avc.py

This PR is template WA for the venc refer encode/avc test case TODO:
update vaapi-fits parameter
align venc refer encode/avc
baseline rebase for the test case update

WA: for media-driver 89c6167 to support B frame on encode/avc part

---

lib/gstreamer/decoderbase.py

The avvideocompare does not work properly if the data is not aligned.  To force alignment, downstream needs to advertise video meta.  Thus, link avvideocompare to fakevideosink to inject video meta into the pipeline.

gst/decode: link avvideocompare to fakevideosink

---

lib/gstreamer/decoderbase.py

Otherwise the decode pipeline will only go as fast as the FPS.  For testing speedup, we want to decode as fast as possible.

gst/decode: sync=0 for fakevideosink

---

lib/gstreamer/va/encoder.py
lib/gstreamer/va/util.py
test/gst-va/encode/av1.py

1, map gf-group-size to bframes, because There is no B frame in AV1 spec. gst-va use gf-group-size to specify golden frame group, which is like the B frames within I/P from Junyan's input
2, add av1 8bit encode test implenent

Gst-va add av1 8bit encode support

---

lib/gstreamer/va/encoder.py

The tilerows and tilecols properties are specified in AV1e tests but encoder base forgot to use them.
Add tilerows and tilecols properties to the gst command-line.

gst/va/encoder: handle tilerows/cols

---

lib/ffmpeg/decoderbase.py

When doing inline psnr/ssim, the raw conversion and output file dump is unnecessary and only adds runtime overhead.
Remove the conversion and file dump to improve inline psnr/ssim speed.

ffmpeg: no dump for inline psnr/ssim

---

lib/caps/ADL/iHD
lib/caps/ATSM/iHD
lib/caps/DG1/iHD
lib/caps/DG2/iHD
lib/caps/MTL/iHD
lib/caps/RKL/iHD
lib/caps/SG1/iHD
lib/caps/TGL/iHD
lib/ffmpeg/util.py
lib/ffmpeg/vaapi/vpp.py
lib/ffmpeg/vppbase.py
lib/mixin/vpp.py
lib/parameters.py
test/ffmpeg-vaapi/vpp/tonemap.py

It is for FFmpeg VA-API only (H2S tonemap in FFmpeg QSV is still WIP, see https://github.com/intel-media-ci/ffmpeg/pull/518)

Add tests for H2S Tonemap

---

lib/gstreamer/transcoderbase.py
lib/gstreamer/va/transcoder.py
test/gst-va/transcode/__init__.py
test/gst-va/transcode/avc.py

1,  [gstreamer-va] add transcoder support in core library
add gst-va transcode support with output support codecs:
- to avc encode
- to hevc 8bit encode
- to jpeg encode
- to av1 encode
- to mpeg2 encode
add vpp scaling support
2, [gst-va] add avc as input for transcode implement

[Gst-va] add transcode support in core library and avc as input for transcode 

---

lib/ffmpeg/qsv/vpp.py
test/ffmpeg-qsv/vpp/tonemap.py

This is used to check HDR-to-SDR added in https://github.com/intel-media-ci/ffmpeg/pull/518

ffmpeg/qsv/vpp: add h2s tonemap tests

---

lib/gstreamer/msdk/transcoder.py
lib/gstreamer/transcoderbase.py

These cases are about implicit va surface sharing between va and msdk, i.e. "vah264dec ! msdkh264enc ! h264parse", in which vah264dec and msdkh264enc sharing va surface via negotiated va memory caps.

gst-msdk: Add surface sharing cases between va and msdk

---

lib/caps/DG2/iHD
lib/ffmpeg/qsv/vpp.py
lib/ffmpeg/vaapi/vpp.py
lib/gstreamer/msdk/vpp.py
lib/gstreamer/va/vpp.py
lib/gstreamer/vaapi/vpp.py
lib/mfx/util.py
lib/mixin/vpp.py

Normalize the test framework sharpen levels so the specified user config vpp level ultimately maps to the same value that middleware sends to the libva driver.
This will enable sharpen refs to be shared across components.
For ffmpeg-vaapi, the passthrough/default level currently fails until the following upstream patches are finished:
https://patchwork.ffmpeg.org/project/ffmpeg/list/?series=9025

vpp/sharpen: normalize vpp sharpen levels

---

lib/ffmpeg/transcoderbase.py

In case of input has audio stream which will influence frame number of output video. The other reason is that vframes for filter showinfo is not accurate. For example, when use 'vframes 1', the output of showinfo will be 2 frames' info. Use all frame number to make sure the otuput will be same for diffferent case.

lib/ffmpeg/transcoderbase: show all frame's HDR info

---

lib/caps/APL/i965
lib/caps/CFL/i965
lib/caps/KBL/i965
lib/caps/SKL/i965

disable avc lp bframes support on APL, CFL, KBL
and SKL which has avc vdenc support platforms
for i965

[i965] disable avc lp bframes support

---

lib/caps/RKL/d3d11
lib/caps/RKL/d3d12
lib/caps/RKL/dxva2
lib/caps/RKL/vaon12
lib/caps/TGL/d3d11
lib/caps/TGL/d3d12
lib/caps/TGL/dxva2

disable avc lp bframes for wind on TGL/RKL
d3d11, d3d12, dxva vaon

[win] disable avc lp bframes for windows on TGL/RKL

---

lib/baseline.py
lib/ffmpeg/encoderbase.py
lib/ffmpeg/qsv/encoder.py
lib/gstreamer/encoderbase.py
lib/metrics2/psnr.py
model/__init__.py
model/encode/__init__.py
model/encode/avc.py
model/encode/util.py
test/ffmpeg-qsv/encode/avc.py

User can add `metric = dict(type='psnr',mode='trendline')` to test case configuration and run tests in the `model/encode` directory.  The model tests will encode the cases using ffmpeg-qsv CQP over various QP and attempt a curve_fit of LN compression ratio  vs. PSNR to find a trendline.  The trendline model parameters will be stored in the baseline directory with `--rebase` flag and then used as the test metric for standard testing in the `test/<mw>/encode` directory.
Additionally, the model trendlines and datapoints are plotted and saved as SVG file in the artifacts.  Those can be retained for further inspection by using the `--artifact-retention 2` flag.
Example:
```shell
vaapi-fits run model/encode/avc.py --pl TGL -vv --rebase --artifact-retention 2
vaapi-fits run …
```

Add Trendline Model Support for AVCe

---

lib/ffmpeg/qsv/encoder.py
lib/ffmpeg/qsv/util.py
model/encode/vp9.py
test/ffmpeg-qsv/encode/vp9.py

1, add ffmpeg-qsv vp9 8bit profile map
2, move ffmpeg-qsv vp9-8 encode test classes to lib
3, add support for vp9 8bit encode trendline models

[Trend Mode] add Vp9 8bit trendline support

---

lib/gstreamer/msdk/transcoder.py
lib/gstreamer/transcoderbase.py
lib/gstreamer/util.py

Also found that there is no format mapping in gstreamer transcoding, e.g. we always set "P010" in test case but we need "P010_10LE" or "p010-10le" in gstreamer pipeline.
Besides, in transcoder get_encoder, profile is always set to "main" for hevc encoder, which cannot work with 10bit, 12bit-like format... So remove that profile hardcode in gst_encoder for transcoding and let gstreamer negotiation to handle the profile.

msdk: Enable HDR transcoding case

---

lib/ffmpeg/qsv/encoder.py
lib/ffmpeg/vaapi/encoder.py
model/encode/vp8.py
test/ffmpeg-vaapi/encode/vp8.py

This one uses ffmpeg-vaapi since qsv does not have vp8e support.

VP8e trendline model support

---

lib/caps/MTL/iHD
lib/ffmpeg/qsv/encoder.py
test/ffmpeg-qsv/encode/vp9.py
test/gst-msdk/encode/vp9.py
test/gst-va/encode/vp9.py

there will no lp mode for MTL encode
add non-lp mode support for vp9 8bit encode for ffmpeg and gstreamer

[MTL] non-low power mode support for vp9 8bit encode

---

lib/mfx/runtime.py

The original design for the Linux
on the windows side don't need ffmpeg-qsv runtime detect

lib/mfx/runtime: skip windows detect runtime

---

lib/parameters.py
test/ffmpeg-qsv/encode/vp9.py
test/ffmpeg-vaapi/encode/vp9.py
test/gst-msdk/encode/vp9.py
test/gst-va/encode/vp9.py
test/gst-vaapi/encode/vp9.py

MTL replace non-low power encode parameters for ffmpeg/gstreamer
gen_vp9_cqp_lp_parameters -> gen_vp9_cqp_parameters
gen_vp9_cbr_lp_parameters -> gen_vp9_cbr_parameters
gen_vp9_vbr_lp_parameters -> gen_vp9_vbr_parameters

Mtl parametrize vp9 8bit enc

---

lib/caps/CFL/i965
lib/caps/KBL/i965

https://github.com/intel/intel-vaapi-driver/blob/master/README#L35-L52

caps: i965 does not support VP9 10bit encode

---

lib/caps/MTL/iHD
lib/ffmpeg/qsv/encoder.py
test/ffmpeg-qsv/encode/10bit/vp9.py
test/ffmpeg-vaapi/encode/10bit/vp9.py
test/gst-msdk/encode/10bit/vp9.py
test/gst-va/encode/10bit/vp9.py
test/gst-vaapi/encode/10bit/vp9.py

1, ffmpeg/gstreamer test add vp9-10bit non-lowpower mode support
2, ffmpeg/gstreamer lib update check for vp9-10bit non-lowpower
3, MTL caps

MTL+ add encode vp9 10bit non-lowpower test path support

---

lib/caps/MTL/iHD

move avc and hevc 8bit/10bit from vdenc test mode to non-lp encode mode

[Caps] MTL move avc and hevc from vdenc to encode

---

.slashrc
requirements.txt

Newer version of setuptools/pip throw error when trying
to install slash 1.12.0 due to more strict dependency
version syntax checks.
The syntax was fixed in slash 1.14.0 (slash commit 6ceffde64970).
Tested vaapi-fits with slash 1.14.0 and it still works well.

Allow Slash 1.14

---

lib/codecs.py
lib/formats.py
lib/metrics.py
lib/metrics2/psnr.py
lib/metrics2/ssim.py
test/ffmpeg-vaapi/encode/10bit/vp9.py
test/ffmpeg-vaapi/encode/vp9.py

The Enum support was introduced in Python 3.4 (https://docs.python.org/3/library/enum.html).
Define a `PixelFormat` enum which combines bitdepth, subsampling, and pixel format.
Define a `Codec` enum.  The bitdepth is omitted from the codec values as it is redundant and unnecessary.  In the current code, we often use strings like `"hevc-10"` and `"hevc-8"` in the codec property.  But after examination, it is not necessary to distinguish it that way and only introduces potential bugs, maintenance overhead and inconsistencies.
These enums will eventually replace hard-coded strings throughout the code to enforce and improve consistency.
These enums are directly comparable to strings for maximum backwards compatibility.  For example:
```python
PixelFormat._NV12 == PixelFormat("NV12") == "NV12" …
```

Define PixelFormat and Codec as enums

---

lib/gstreamer/va/decoder.py
lib/gstreamer/va/encoder.py
test/gst-va/decode/10bit/av1.py
test/gst-va/decode/10bit/hevc.py
test/gst-va/decode/10bit/vp9.py
test/gst-va/decode/12bit/hevc.py
test/gst-va/decode/12bit/vp9.py
test/gst-va/decode/av1.py
test/gst-va/decode/avc.py
test/gst-va/decode/hevc.py
test/gst-va/decode/jpeg.py
test/gst-va/decode/mpeg2.py
test/gst-va/decode/vp8.py
test/gst-va/decode/vp9.py

On some multi-gpu systems the default decoder element
may not exist but the device specific decoder element
does.
For example, CFL+DG2 will not have a default "vaav1dec"
element but has a "varenderD129av1dec" element.  Thus,
a hard-coded slash.requires for the default decode
element will cause av1 decode cases to be unintentionally
skipped on DG2.
To fix this, define a codec specialized class template so
that the device specific element name can be resolved
before the slash.requires check.

gst-va: resolve hwdevice path in decoder element name before slash.requires

---

lib/ffmpeg/qsv/encoder.py
lib/gstreamer/msdk/encoder.py

1, based on ICQ define in vpl spec    https://spec.oneapi.io/onevpl/latest/API_ref/VPL_structs_cross_component.html#id10
its value is rang in [1, 51], but qp input is [0, 255], that's why some icq cases failed for ffmpeg-qsv/gst-msdk so there needs a map
2, for gst-msdk, rcmode was replaced by "rate-control =icq hardware=true", so we needs to use super().rcmode for "if", otherwise it still run cmdline with cqp mode

Fixing ffmpeg-qsv/gst-msdk av1 icq wrong cmd opt rang

---

test/ffmpeg-qsv/vpp/csc.py
test/ffmpeg-vaapi/vpp/csc.py
test/gst-msdk/vpp/csc.py
test/gst-vaapi/vpp/csc.py

This change references the number of the previous PR: 582

ffmpeg/gstreamer: use correct test spec in csc/r2r

---

lib/ffmpeg/transcoderbase.py

ffmpeg vsync option renamed to fps_mode

ffmpeg/xcode: replace vsync with fps_mode

---

lib/ffmpeg/decoderbase.py

The -autoscale 0 option no longer works and causes pipeline to error/abort.
The correct usage, apparently, is to use -noautoscale.
```
Since FFMpeg commit 25c98566e8a45b50415c80ca6450282f2ec0657a
Author: Anton Khirnov <anton@khirnov.net>
Date:   Fri Dec 15 02:31:03 2023 +0100
fftools/ffmpeg_opt: drop HAS_ARG from auto{scale,rotate}
```

ffmpeg/decode: fix autoscale usage break

---

lib/ffmpeg/encoderbase.py
test/ffmpeg-vaapi/decode/jpeg.py

Explicitly use tv scale/color range for JPEG decode to make ffmpeg-vaapi consistent with all other tested middleware plugins.
Since 8b76bae8961c
VIZ-20450

ffmpeg/jpeg: use tv scale/color range

---

model/encode/10bit/hevc.py

Use a valid QP range accepted by the iHD driver for HEVC 10bit.
Unfortunately, there is still a bug in ffmpeg and vpl that incorrectly forces QP in the wrong range...
See https://github.com/oneapi-src/oneVPL-intel-gpu/issues/297
Thus, until the issue is fixed, the ffmpeg-qsv encoder code needs to be modified, manually, to remove the QP range constraints so that the requested values can propogate to vpl and the driver to properly generate a trendline model.

model: update hevc 10bit QP list

---

lib/gstreamer/vaapi/encoder.py

The vaapidecodebin automatically inserts a vaapipostproc into the pipeline which always selects NV12 output.  This causes issues when decoding non 8-bit and non 420 pixel formats.  For example, Y410 (444) coded source can be decoded directly to Y410 output.  But the automatic vpp insertion from vaapidecodebin creates a downsampling CSC operation to NV12 and causes the output to lose detail.
This fixes a VP9 10bit 444 encode regression caused by improperly decoded source file.
Relates To: VIZ-20620
cc: @wenqingx @Hangjie22Coder

gst/vaapi: do not rank vaapidecodebin

---

lib/caps/DG2/d3d12

D3D12 should use encoder instead of vdenc.

caps: update d3d12 encoder caps for DG2

---

.slashrc
lib/artifacts.py
lib/ffmpeg/encoderbase.py
lib/ffmpeg/vppbase.py
lib/gstreamer/encoderbase.py
lib/gstreamer/vppbase.py

Register all coded test source files before starting
the session.
When a source is registered multiple times, only the
number of requested frames is updated if it's more than
the previous registration.  This helps optimize decoded
cache so that we only have to decode the source once,
regardless of how many frames each case is going to
use.
VIZ-20591

assets: register test case sources before start

---

lib/caps/ADL/iHD
test/gst-msdk/encode/10bit/vp9.py

Reverts intel/vaapi-fits#649
ADL does not have VP9 VME, only VDENC

Revert "[caps] update ADL/iHD caps"

---

lib/gstreamer/transcoderbase.py

For dma xcode cases, use the vpp element from the plugin that is being tested (e.g. msdkvpp for msdk xcode, vapostproc for va xcode, etc.).
cc: @wenqingx

gst/xcode: do not hardcode vpp element for dma

---

lib/gstreamer/transcoderbase.py

The gst plugins should be able to handle input with undefined fps.  If we force fps in the pipeline, then we hide a bug in gst-va.
Thus, don't specify fps explicitly and let gst-va fix it properly.
VIZ-20689
This reverts commit 5f74156a6f6bcaa6e9cd7a93a93fd72b27e0dc46.
cc: @HeJunyan @wenqingx

Revert "gst/xcode: specify decoder fps"

---

lib/gstreamer/transcoderbase.py
lib/gstreamer/util.py
lib/gstreamer/vaapi/transcoder.py

AV1 and VP9 encode fails if no framerate is
provided by upstream pipeline element.
VIZ-20689
cc: @wenqingx @HeJunyan

gst/xcode: set explicit input fps if unknown

---

lib/ffmpeg/vaapi/encoder.py

...so user config does not need to workaround it with a post_validate callback.
cc: @wenqingx

ffmpeg/vaapi/encode: skip tilecols/rows < 1

---

lib/ffmpeg/transcoderbase.py
lib/ffmpeg/util.py
lib/gstreamer/msdk/transcoder.py
lib/gstreamer/transcoderbase.py
lib/gstreamer/va/transcoder.py
lib/gstreamer/vaapi/transcoder.py

The internally supplied psnr filter from the test framework can be slow
and memory intensive.
Thus, use the middleware provided psnr filter, inline, on the generated test command-lines, instead.
Also, we no longer need to dump the source and result yuv to disk (which
can be big and slow, too).
The inline psnr can speed up xcode test cases significantly.
Also, fixed a few issues in gst xcode requirements and check assumptions.
cc: @wenqingx

Transcode inline metrics

---

lib/gstreamer/msdk/transcoder.py
lib/gstreamer/transcoderbase.py
lib/gstreamer/va/transcoder.py
lib/gstreamer/vaapi/transcoder.py
test/gst-vaapi/transcode/av1.py

* gst/xcode: choose decode demuxer based on file ext
In https://github.com/intel/vaapi-fits/pull/662 we made
the assumption that the user test config will always use
a webm (matroska) formatted input source file for AV1
xcode.
However, our internal AV1 test cases use ivf input
source files.  Unfortunately, gstreamer does not have
a ivf muxer for the encode side of the pipeline. Nor is
it able to discover an elementary AV1 (or VP9) file.
Thus, when AV1 (or VP9) is the target output format,
we still need to use the matroska container format
(matroskamux).
Thus, dynamically choose the proper demuxer to decode
the input source file and the output result files
based on the filename extension.
* gst-vaapi/xcode: add AV1 xcode support
cc: @wenqingx

gst/xcode: fix AV1 demux assumption and add gst-vaapi AV1 xcode test

---

.github/workflows/unit.yml
requirements.txt

Add GitHub workflow to execute non-gpu unit tests on the GitHub runners.

gh/workflows: add non-gpu unit tests

---

lib/ffmpeg/qsv/encoder.py
lib/ffmpeg/util.py
lib/mfx/api.py
lib/parameters.py
test/ffmpeg-qsv/encode/av1.py
test/ffmpeg-qsv/encode/avc.py
test/ffmpeg-qsv/encode/hevc.py

add string api support for ffmpeg-qsv
1, enable on DG2 fistly
2, the patch comments will update later after some times reviews done

[ffmpeg-qsv] add string api support

---

lib/mixin/vpp.py

Revert "Enhance PSNR Check for Luma (Y) Channel in VPP Sharpen Filter"
