intel/vaapi-fits

test/ffmpeg-qsv/decode/vp9.py

add ffmpeg-qsv vp9 10bit decode

---

baseline/default
test/ffmpeg-vaapi/decode/10bit/__init__.py
test/ffmpeg-vaapi/decode/10bit/hevc.py
test/ffmpeg-vaapi/decode/10bit/vp9.py
test/ffmpeg-vaapi/decode/decoder.py
test/ffmpeg-vaapi/decode/hevc.py
test/ffmpeg-vaapi/decode/mpeg2.py
test/ffmpeg-vaapi/decode/vc1.py
test/ffmpeg-vaapi/decode/vp8.py
test/ffmpeg-vaapi/decode/vp9.py
test/ffmpeg-vaapi/encode/10bit/__init__.py
test/ffmpeg-vaapi/encode/10bit/hevc.py
test/ffmpeg-vaapi/encode/avc.py
test/ffmpeg-vaapi/encode/encoder.py
test/ffmpeg-vaapi/encode/jpeg.py
test/ffmpeg-vaapi/encode/mpeg2.py
test/ffmpeg-vaapi/encode/vp8.py
test/ffmpeg-vaapi/encode/vp9.py
test/ffmpeg-vaapi/util.py
tools/xform-baseline-1.sh

Refactor ffmpeg-vaapi encode/decode tests to improve code reuse and sharing.
10bit  tests have moved into its own sub-directory.
Added a tools/xform-baseline-1.sh script to convert old baseline test names to new test names.

Share common code for ffmpeg-vaapi encode/decode tests

---

test/ffmpeg-qsv/util.py
test/ffmpeg-vaapi/util.py

add 422H 422V 444P Y800 in ffmpeg jpeg decode support

---

config/default

config/default: improve assets error message

---

.slashrc
lib/platform.py

Include some platform information in the results.xml file.

Add platform info to results.xml

---

test/ffmpeg-qsv/encode/mpeg2.py
test/ffmpeg-vaapi/encode/encoder.py
test/ffmpeg-vaapi/encode/mpeg2.py
test/gst-msdk/encode/mpeg2.py
test/gst-vaapi/encode/mpeg2.py

map qp to 2-62 for gst-vaapi
map qp to 0-51 for gst-msdk

encode/mpeg2: map qp value into valid range

---

test/ffmpeg-vaapi/transcode/transcoder.py

ffmpeg-vaapi/transcode: video filter option corrected for SWtoHW tests

---

baseline/default
test/ffmpeg-qsv/decode/10bit/__init__.py
test/ffmpeg-qsv/decode/10bit/hevc.py
test/ffmpeg-qsv/decode/10bit/vp9.py
test/ffmpeg-qsv/decode/avc.py
test/ffmpeg-qsv/decode/decoder.py
test/ffmpeg-qsv/decode/hevc.py
test/ffmpeg-qsv/decode/jpeg.py
test/ffmpeg-qsv/decode/mpeg2.py
test/ffmpeg-qsv/decode/vc1.py
test/ffmpeg-qsv/decode/vp9.py
test/ffmpeg-qsv/encode/10bit/__init__.py
test/ffmpeg-qsv/encode/10bit/hevc.py
test/ffmpeg-qsv/encode/avc.py
test/ffmpeg-qsv/encode/encoder.py
test/ffmpeg-qsv/encode/jpeg.py
test/ffmpeg-qsv/encode/mpeg2.py
test/ffmpeg-qsv/util.py
tools/xform-baseline-1.sh

Improve code reuse in ffmpeg-qsv encode and decode tests.

ffmpeg-qsv: refactor enc/dec tests for code reuse

---

lib/framereader.py
lib/metrics.py
test/gst-msdk/util.py
test/gst-msdk/vpp/csc.py
test/gst-vaapi/util.py
test/gst-vaapi/vpp/csc.py

support user-specified test standrad for csc and support format ARGB framereader.

Csc optimize

---

test/ffmpeg-qsv/util.py
test/ffmpeg-qsv/vpp/csc.py
test/ffmpeg-vaapi/util.py
test/ffmpeg-vaapi/vpp/csc.py

ffmpeg vpp csc feature support

---

lib/parameters.py
test/ffmpeg-qsv/encode/hevc.py
test/ffmpeg-vaapi/encode/hevc.py

ffmpeg-vaapi/qsv hevc 8bit low_power encode support

---

test/gst-msdk/transcode/__init__.py
test/gst-msdk/transcode/avc.py
test/gst-msdk/transcode/hevc.py
test/gst-msdk/transcode/mpeg2.py
test/gst-msdk/transcode/transcoder.py
test/gst-msdk/transcode/vc1.py
test/gst-vaapi/transcode/__init__.py
test/gst-vaapi/transcode/avc.py
test/gst-vaapi/transcode/hevc.py
test/gst-vaapi/transcode/mpeg2.py
test/gst-vaapi/transcode/transcoder.py
test/gst-vaapi/transcode/vc1.py

HWtoHW, HWtoSW and SWtoHW avc transcoding support for gst-vaapi

Transcode enable

---

.slashrc
lib/common.py
test/ffmpeg-qsv/decode/decoder.py
test/ffmpeg-qsv/transcode/transcoder.py
test/ffmpeg-vaapi/decode/decoder.py
test/ffmpeg-vaapi/transcode/transcoder.py
test/gst-msdk/decode/decoder.py
test/gst-msdk/transcode/transcoder.py
test/gst-vaapi/decode/decoder.py
test/gst-vaapi/transcode/transcoder.py

1. test timeout value can be paased from user-spec.
2. This is useful for handling larger 4K test streams

test timeout through user-spec added

---

lib/parameters.py
test/gst-msdk/vpp/transpose.py

transpose: mirroring + rotation

vpp: enable transpose for gst-msdk

---

baseline/default
test/gst-msdk/encode/10bit/__init__.py
test/gst-msdk/encode/10bit/hevc.py
test/gst-msdk/encode/avc.py
test/gst-msdk/encode/encoder.py
test/gst-msdk/encode/jpeg.py
test/gst-msdk/encode/mpeg2.py
test/gst-msdk/encode/vp8.py
test/gst-msdk/util.py
tools/xform-baseline-1.sh

Already test this commit with vaapi-fits-full on CFL
Please review , thanks.

gst-msdk/encode: refactor tests for better code reuse

---

lib/parameters.py
test/ffmpeg-qsv/encode/hevc.py
test/ffmpeg-vaapi/encode/hevc.py
test/gst-msdk/encode/hevc.py
test/gst-vaapi/encode/encoder.py
test/gst-vaapi/encode/hevc.py

add cbr/vbr support for ffmpeg
cqp/cbr/vbr support for gstreamer

hevc vdenc: add cqp/cbr/vbr support

---

test/ffmpeg-qsv/transcode/transcoder.py
test/ffmpeg-vaapi/transcode/transcoder.py
test/gst-msdk/transcode/transcoder.py
test/gst-vaapi/transcode/transcoder.py

Support transcode vpp scaling in ffmpeg and gstreamer tests.
This supersedes #57

Transcode: Add scale support

---

test/ffmpeg-qsv/encode/10bit/hevc.py
test/ffmpeg-vaapi/encode/10bit/hevc.py

hevc 10bit vdenc: add ffmpeg support

---

test/gst-msdk/encode/10bit/hevc.py
test/gst-vaapi/encode/10bit/hevc.py

test: enable hevc 10bit vdenc for gstreamer

---

lib/parameters.py
test/ffmpeg-qsv/encode/avc.py
test/ffmpeg-qsv/encode/encoder.py

avc enc: add look_ahead test support

---

test/ffmpeg-vaapi/util.py
test/ffmpeg-vaapi/vpp/transpose.py
test/gst-msdk/util.py

ffmpeg-vaapi/vpp: add transpose support

---

test/gst-msdk/encode/avc.py
test/gst-msdk/encode/encoder.py

avce: add look_ahead test support for gst-msdk

---

test/gst-msdk/encode/10bit/hevc.py
test/gst-msdk/encode/avc.py
test/gst-msdk/encode/encoder.py
test/gst-msdk/encode/hevc.py
test/gst-msdk/encode/jpeg.py
test/gst-msdk/encode/mpeg2.py
test/gst-vaapi/encode/10bit/hevc.py
test/gst-vaapi/encode/avc.py
test/gst-vaapi/encode/encoder.py
test/gst-vaapi/encode/hevc.py
test/gst-vaapi/encode/jpeg.py
test/gst-vaapi/encode/mpeg2.py

test: enable r2r encoding test for gstreamer

---

test/gst-msdk/decode/decoder.py
test/gst-msdk/decode/jpeg.py
test/gst-msdk/decode/mpeg2.py
test/gst-msdk/decode/vc1.py
test/gst-vaapi/decode/decoder.py
test/gst-vaapi/decode/jpeg.py
test/gst-vaapi/decode/mpeg2.py
test/gst-vaapi/decode/vc1.py

test: enable r2r decoding test for gstreamer

---

test/gst-msdk/encode/encoder.py

enc: add bitrate check for "la_vbr" mode

---

.slashrc
lib/common.py
lib/metrics.py
test/ffmpeg-qsv/decode/decoder.py
test/ffmpeg-qsv/encode/encoder.py
test/ffmpeg-vaapi/decode/decoder.py
test/ffmpeg-vaapi/encode/encoder.py
test/gst-msdk/decode/decoder.py
test/gst-msdk/encode/encoder.py
test/gst-vaapi/decode/decoder.py
test/gst-vaapi/encode/encoder.py

Timing instrumentation of several critical functions with results logged to test details.

add timing details for various functions

---

baseline/default
lib/platform.py
test/gst-vaapi/util.py
test/gst-vaapi/vpp/mirroring.py

Depends on:
https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi/merge_requests/74
Test:
```
$ GST_VAAPI_ALL_DRIVERS=1 LIBVA_DRIVER_NAME=iHD vaapi-fits run test/gst-vaapi/vpp/mirroring.py
```

gst-vaapi/vpp: add mirror test

---

lib/metrics.py

Previously, ssim and psnr metrics would append every
frame of yuv data from the source file and output file
into the parallel pool all at once.  This required that
both of the entire raw yuv files could fit into available
memory (physical and swap).  However, the higher the
resolution and number of frames, the higher the likelihood
that it will create heavy swapping situations or OOM.
Thus, limit these metrics to a maximum of 50% of physical
system memory usage in the parallel pool at any given time.

metrics: cap memory usage of parallel metrics

---

baseline/default
test/gst-vaapi/vpp/brightness.py
test/gst-vaapi/vpp/contrast.py
test/gst-vaapi/vpp/csc.py
test/gst-vaapi/vpp/deinterlace.py
test/gst-vaapi/vpp/denoise.py
test/gst-vaapi/vpp/hue.py
test/gst-vaapi/vpp/mirroring.py
test/gst-vaapi/vpp/saturation.py
test/gst-vaapi/vpp/scale.py
test/gst-vaapi/vpp/sharpen.py
test/gst-vaapi/vpp/vpp.py
tools/xform-baseline-1.sh

refactor vpp test script and enable r2r vpp test for gst-vaapi

---

test/ffmpeg-qsv/util.py
test/ffmpeg-qsv/vpp/brightness.py
test/ffmpeg-qsv/vpp/contrast.py
test/ffmpeg-qsv/vpp/csc.py
test/ffmpeg-qsv/vpp/deinterlace.py
test/ffmpeg-qsv/vpp/denoise.py
test/ffmpeg-qsv/vpp/hue.py
test/ffmpeg-qsv/vpp/saturation.py
test/ffmpeg-qsv/vpp/scale.py
test/ffmpeg-qsv/vpp/sharpen.py
test/ffmpeg-qsv/vpp/vpp.py
test/ffmpeg-vaapi/util.py
test/ffmpeg-vaapi/vpp/brightness.py
test/ffmpeg-vaapi/vpp/contrast.py
test/ffmpeg-vaapi/vpp/csc.py
test/ffmpeg-vaapi/vpp/deinterlace.py
test/ffmpeg-vaapi/vpp/denoise.py
test/ffmpeg-vaapi/vpp/hue.py
test/ffmpeg-vaapi/vpp/saturation.py
test/ffmpeg-vaapi/vpp/scale.py
test/ffmpeg-vaapi/vpp/sharpen.py
test/ffmpeg-vaapi/vpp/transpose.py
test/ffmpeg-vaapi/vpp/vpp.py
tools/xform-baseline-1.sh

Use common vpp classes for ffmpeg vpp tests

refactor ffmpeg vpp for code reuse

---

lib/baseline.py
lib/metrics.py
test/ffmpeg-qsv/vpp/brightness.py
test/ffmpeg-qsv/vpp/contrast.py
test/ffmpeg-qsv/vpp/denoise.py
test/ffmpeg-qsv/vpp/hue.py
test/ffmpeg-qsv/vpp/saturation.py
test/ffmpeg-qsv/vpp/sharpen.py
test/ffmpeg-vaapi/vpp/brightness.py
test/ffmpeg-vaapi/vpp/contrast.py
test/ffmpeg-vaapi/vpp/denoise.py
test/ffmpeg-vaapi/vpp/hue.py
test/ffmpeg-vaapi/vpp/saturation.py
test/ffmpeg-vaapi/vpp/sharpen.py
test/gst-msdk/vpp/brightness.py
test/gst-msdk/vpp/contrast.py
test/gst-msdk/vpp/denoise.py
test/gst-msdk/vpp/hue.py
test/gst-msdk/vpp/saturation.py
test/gst-msdk/vpp/sharpen.py
test/gst-vaapi/vpp/brightness.py
test/gst-vaapi/vpp/contrast.py
test/gst-vaapi/vpp/denoise.py
test/gst-vaapi/vpp/hue.py
test/gst-vaapi/vpp/saturation.py
test/gst-vaapi/vpp/sharpen.py

Minor cleanup and refactoring

---

baseline/default
config/vpp.default
lib/caps/APL/i965
lib/caps/APL/iHD
lib/caps/BSW/i965
lib/caps/CFL/i965
lib/caps/CFL/iHD
lib/caps/GLK/i965
lib/caps/ICL/iHD
lib/caps/KBL/i965
lib/caps/KBL/iHD
lib/caps/SKL/i965
lib/caps/SKL/iHD
lib/caps/WHL/iHD
lib/parameters.py
test/gst-vaapi/vpp/crop.py
test/gst-vaapi/vpp/vpp.py

VPP crop supported in gstreamer-vaapi since
commit 2f0f5e1ef9e8

gst-vaapi/vpp: add crop test

---

lib/metrics.py

lib/metrics: add MSE/NRMSE metrics

---

test/gst-msdk/transcode/transcoder.py

The videoconvert element can slow down transcode pipeline by
~6x in many cases.  Thus, eliminate videoconvert usage
where possible and use NV12 as default comparison format.

gst-msdk/transcode: eliminate videoconvert and use NV12 default

---

test/gst-msdk/transcode/transcoder.py

add missing blank space to fix syntax error

---

lib/parameters.py
test/ffmpeg-vaapi/encode/encoder.py
test/ffmpeg-vaapi/encode/hevc.py

add test_level for ICL- test_level_8k for ICL+

ffmpeg-vaapi: add level 6.2 test

---

test/gst-msdk/vpp/crop.py
test/gst-msdk/vpp/vpp.py

Depends on https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/issues/1097

gst-msdk/vpp: add crop test

---

lib/parameters.py
test/gst-msdk/encode/encoder.py
test/gst-msdk/encode/vp9.py

This commit is based on https://github.com/intel/vaapi-fits/pull/102

vp9_lp: enable vp9_lp encoding for gst-msdk

---

lib/caps/CML/iHD

lib/caps: add CML support

---

lib/caps/GLK/iHD

Caps: add GLK iHD support

---

test/gst-msdk/encode/10bit/vp9.py

enable vp9 10bit encoding(vdenc) test for gst-msdk.

vp9_lp enc:enable vp9_lp 10bit encoding for gst-msdk

---

lib/caps/ICL/iHD
lib/caps/TGL/iHD
lib/parameters.py
test/ffmpeg-vaapi/encode/encoder.py
test/ffmpeg-vaapi/encode/hevc.py

Added need VME "low delay b" feature and ffmpeg-vaapi HEVC 8bit  vme low delay b encode support

Added VME "low delay b" support and ffmpeg-vaapi HEVC 8bit 

---

test/ffmpeg-qsv/encode/encoder.py
test/ffmpeg-qsv/encode/hevc.py
test/gst-msdk/encode/hevc.py

Added Hevc 8bit "low delay b" implementation for gst-msdk and ffmpeg-qsv cqp/cbr/vbr

Added Hevc 8bit "low delay b" implementation for gst-msdk and ffmpeg-qsv

---

test/ffmpeg-qsv/transcode/transcoder.py
test/gst-msdk/transcode/transcoder.py

Add transcode vme hevc 8bit ldb for Gst-msdk and ffmpeg-qsv implementation

Transcode vme hevc 8bit ldb for Gst-msdk and ffmpeg-qsv implementation

---

test/ffmpeg-vaapi/encode/10bit/vp9.py

enable vp9 10bit encoding(vdenc) test for ffmpeg-vaapi.

vp9_lp enc:enable vp9_lp 10bit encoding for ffmpeg-vaapi

---

test/ffmpeg-vaapi/encode/10bit/hevc.py

add vme "low delay b" implementation for hevc 10bit
yuv420 cqp/cbr/vbr encode for ffmpeg-vaapi testing

ffmpeg-vaapi: add hevc-10 vme lowdelayb implementation

---

lib/parameters.py

Allow user config to set either method or rate
and variate the other for deinterlace tests.
Examples for previous accepted syntax:
```
modes = [dict(method = "bob", rate = "frame"),] # "bob" method with "frame" rate
modes = [
dict(method = "bob", rate = "frame"),
dict(method = "weave", rate = "field"),
] # "bob" method with "frame" rate AND "weave" method with "field" rate.
```
Examples for additional syntax provided by this patch :
```
modes = [dict(rate = "frame"),] # all default methods with "frame" rate.
modes = [dict(method = "bob"),] # "bob" method with all default rates.
```

parameters: support DI method or rate variation

---

test/ffmpeg-qsv/decode/12bit/__init__.py
test/ffmpeg-qsv/decode/12bit/hevc.py
test/ffmpeg-qsv/util.py

HEVC 12bit P012 format support for ffmpeg-qsv

Added HEVC 12bit P012 format support for ffmpeg qsv

---

.travis.yml
requirements.txt

add travis config

---

test/gst-msdk/encode/encoder.py
test/gst-msdk/util.py

Added HEVC 8bit vdenc 444 ayuv cqp and gst-msdk cqp encode support

HEVC 8bit vdenc 444 ayuv cqp and gst-msdk cqp encode support

---

lib/caps/DG1/iHD
lib/caps/DG1/info

Platform Caps: added DG1 support

---

lib/formats.py

formats: handle RGB formats in get_bit_depth

---

test/gst-vaapi/util.py

map main444-10 to main-10-444 for gst-vaapi

enabled main444-10 map for gst-vaapi

---

test/gst-vaapi/decode/12bit/__init__.py
test/gst-vaapi/decode/12bit/hevc.py
test/gst-vaapi/util.py

gst-vaapi 12bit decode implementation 
P012 format map for gst-vaapi
hevc-12bit 420 profile map for gst-vaapi

Gst vaapi supported hevc 12bit 420 decode

---

lib/caps/JSL/iHD
lib/caps/JSL/info

Add JSL Caps support for test spec and gen define

Add JSL Caps support for test spec and gen define

---

tools/bdrate

1. filters
2. refs
3. junit output

Bdrate enhancements

---

test/ffmpeg-vaapi/decode/12bit/__init__.py
test/ffmpeg-vaapi/decode/12bit/hevc.py
test/ffmpeg-vaapi/util.py

ffmpeg-vaapi added hevc 12bit 420 decode support

ffmpeg-vaapi added hevc 12bit 420 decode support

---

test/gst-vaapi/decode/12bit/vp9.py

removed an annotation in the gst-vaapi vp9-12 dec

---

lib/ffmpeg/qsv/util.py

added hevc 12bit decode 422 support

ffmpeg-qsv added hevc-12 422 dec support

---

lib/caps/DG1/iHD

DG1 added AV1 decode caps support

---

lib/caps/TGL/iHD
test/gst-msdk/decode/10bit/av1.py

1, TGL caps
2, av1 10bit decode
3, profile map

gst-msdk add av1 10bit decode support

---

test/ffmpeg-vaapi/decode/10bit/av1.py

ffmpeg-vaapi add av1-10 decode support

added ffmpeg-vaapi av1-10 decode support

---

test/ffmpeg-qsv/decode/10bit/av1.py

ffmpeg-qsv add av1-10 decode support

added ffmpeg-qsv av1-10 decode support

---

lib/caps/DG1/iHD
lib/caps/RKL/iHD
lib/caps/TGL/iHD
lib/gstreamer/msdk/encoder.py
lib/gstreamer/msdk/util.py
lib/gstreamer/vaapi/encoder.py
lib/gstreamer/vaapi/util.py

1, Caps: TGL/RKL/DG1
2, gst-msdk add hevc scc encode support
3, gst-vaapi add hevc scc encode support

gstreamer msdk/vaapi add hevc scc encode support

---

lib/ffmpeg/qsv/encoder.py
lib/ffmpeg/qsv/util.py
lib/ffmpeg/vaapi/encoder.py
lib/ffmpeg/vaapi/util.py
test/ffmpeg-vaapi/encode/hevc.py

1, ffmpeg-vaapi hevc scc encode enabling
2, ffmpeg-qsv hevc scc encode enabling

ffmpeg-vaapi/qsv hevc scc encode enabling

---

lib/ffmpeg/qsv/util.py
lib/ffmpeg/vaapi/util.py
test/ffmpeg-vaapi/encode/hevc.py

ffmpeg-qsv/vaapi hevc scc enc 444 enabling

ffmpeg-qsv/vaapi hevc scc enc 444 enabling

---

lib/caps/SG1/iHD
lib/caps/SG1/info

Caps: add sg1 support

---

lib/gstreamer/vaapi/util.py

added hevc/vp9 12bit 444 support

gst-vaapi added hevc/vp9 12bit 444 support

---

lib/caps/DG1/iHD
lib/caps/RKL/iHD
lib/caps/SG1/iHD

added av1-10 and vp9-12bit decode for sg1/dg1/rkl

Caps: added av1-10 and vp9-12bit decode for sg1/dg1/rkl

---

lib/gstreamer/msdk/encoder.py

added vp9 8bit enc ayuv format support

gst-msdk added vp9 8bit enc ayuv format support

---

lib/ffmpeg/qsv/util.py

add ffmpeg-qsv hevc-8 enc 444 profile map

ffmpeg-qsv hevc-8 enc add 444 profile map

---

lib/gstreamer/vaapi/util.py
test/gst-vaapi/decode/av1.py

Gst-vaapi support av1 decode 8bit

Gst-vaapi support av1 decode 8bit

---

test/gst-vaapi/decode/10bit/av1.py

added av1 10bit decode support

gst-vaapi added av1 10bit decode support

---

lib/ffmpeg/vaapi/util.py
test/ffmpeg-vaapi/encode/hevc.py

ffmpeg vaapi added hevc 8bit 444 profile support

ffmpeg vaapi added hevc 8bit 444 profile support

---

lib/ffmpeg/qsv/util.py

added hevc-10bit 444 enc profile map

ffmpeg-qsv added hevc-10bit 444 enc profile map

---

.slashrc

when GPU reset failed, set current case to error status

update .slashrc for GPU reset failed detect

---

lib/platform.py

If VAAPI_FITS_CAPS environment variable is defined, then
try to load caps from this path.  If no caps found, then
fallback to library caps path.

User defined caps

---

lib/caps/ADL/iHD
lib/caps/ADL/info

Caps add ADL platform support

---

.slashrc
blacklist/README.md

This feature will directory mark test case to failed

update .slashrc: to add blacklist feature

---

.slashrc
lib/ffmpeg/qsv/decoder.py
lib/ffmpeg/qsv/encoder.py
lib/ffmpeg/qsv/transcoder.py
lib/ffmpeg/qsv/vpp.py
lib/ffmpeg/vaapi/decoder.py
lib/ffmpeg/vaapi/encoder.py
lib/ffmpeg/vaapi/transcoder.py
lib/ffmpeg/vaapi/vpp.py
lib/gstreamer/msdk/decoder.py
lib/gstreamer/msdk/encoder.py
lib/gstreamer/msdk/transcoder.py
lib/gstreamer/msdk/vpp.py
lib/gstreamer/vaapi/decoder.py
lib/gstreamer/vaapi/encoder.py
lib/gstreamer/vaapi/transcoder.py
lib/gstreamer/vaapi/vpp.py

Update .slashrc to add parameter for render device

---

lib/caps/ADL/iHD
lib/caps/DG1/iHD
lib/caps/RKL/iHD
lib/caps/SG1/iHD
lib/caps/TGL/iHD

added main still picture feature support on Gen12

Caps: added main still feature support on Gen12

---

.slashrc
.travis.yml
README.md
requirements.txt

require Slash 1.12.0

---

lib/gstreamer/msdk/transcoder.py
lib/gstreamer/transcoderbase.py
lib/gstreamer/vaapi/transcoder.py

Add a transcoder base class for gstreamer to share
common code between msdk and vaapi elements.

lib/gstreamer: add common transcoder base

---

lib/gstreamer/va/__init__.py
lib/gstreamer/va/decoder.py
lib/gstreamer/va/util.py
lib/gstreamer/va/vpp.py
test/gst-va/__init__.py
test/gst-va/decode/10bit/__init__.py
test/gst-va/decode/10bit/av1.py
test/gst-va/decode/10bit/hevc.py
test/gst-va/decode/10bit/vp9.py
test/gst-va/decode/12bit/__init__.py
test/gst-va/decode/12bit/hevc.py
test/gst-va/decode/12bit/vp9.py
test/gst-va/decode/__init__.py
test/gst-va/decode/av1.py
test/gst-va/decode/avc.py
test/gst-va/decode/hevc.py
test/gst-va/decode/mpeg2.py
test/gst-va/decode/vp9.py
test/gst-va/vpp/__init__.py
test/gst-va/vpp/brightness.py
test/gst-va/vpp/contrast.py
test/gst-va/vpp/csc.py
test/gst-va/vpp/denoise.py
test/gst-va/vpp/hue.py
test/gst-va/vpp/mirroring.py
test/gst-va/vpp/rotation.py
test/gst-va/vpp/sharpen.py
test/gst-va/vpp/transpose.py

This PR base on https://github.com/intel/vaapi-fits/pull/292

Add test context gst-va

---

test/gst-va/vpp/sharpen.py

fix typo on gst-va

---

lib/gstreamer/msdk/vpp.py
lib/gstreamer/va/vpp.py
lib/gstreamer/vaapi/vpp.py
test/gst-msdk/vpp/brightness.py
test/gst-msdk/vpp/contrast.py
test/gst-msdk/vpp/hue.py
test/gst-msdk/vpp/saturation.py
test/gst-va/vpp/brightness.py
test/gst-va/vpp/contrast.py
test/gst-va/vpp/denoise.py
test/gst-va/vpp/hue.py
test/gst-va/vpp/sharpen.py
test/gst-vaapi/vpp/brightness.py
test/gst-vaapi/vpp/contrast.py
test/gst-vaapi/vpp/denoise.py
test/gst-vaapi/vpp/hue.py
test/gst-vaapi/vpp/saturation.py
test/gst-vaapi/vpp/sharpen.py

Easier to see all map ranges in one place and will simplify maintenance.

gst/vpp: map levels in base class

---

test/gst-va/vpp/saturation.py

test/gst-va/vpp: add saturation test

---

test/gst-va/decode/10bit/av1.py

gst-va: fixed av1 obu ext issue

---

baseline/default/vpp.composite/default.test
config/vpp.default
lib/caps/ADL/iHD
lib/caps/APL/iHD
lib/caps/CFL/iHD
lib/caps/CML/iHD
lib/caps/DG1/iHD
lib/caps/EHL/iHD
lib/caps/ICL/iHD
lib/caps/JSL/iHD
lib/caps/KBL/iHD
lib/caps/RKL/iHD
lib/caps/SG1/iHD
lib/caps/SKL/iHD
lib/caps/TGL/iHD
lib/caps/WHL/iHD
lib/gstreamer/vaapi/vpp.py
lib/gstreamer/vppbase.py
lib/mixin/vpp.py
test/gst-vaapi/vpp/composite.py

The test is for simple composite cases to minimally cover gstreamer-vaapi vaapioverlay (vpp blend feature).

gst-vaapi simple vpp composite test support

---

test/gst-va/decode/vp8.py

Add gst-va/decode/vp8 support

---

lib/ffmpeg/qsv/transcoder.py
lib/ffmpeg/qsv/util.py
lib/ffmpeg/vaapi/transcoder.py
lib/ffmpeg/vaapi/util.py
lib/gstreamer/transcoderbase.py
lib/gstreamer/util.py

Validate transcoded resolution

---

test/self/empty.py

Useful for running --rebase to force baseline files
to be loaded and rewritten using our internal JSON
encoder options (e.g. precision, indentation,
and sorting) without changing the actual references.

test/self/empty: empty test

---

lib/gstreamer/msdk/transcoder.py

The msdk plugins have rank "none (0)".  Thus, they will be skipped by the
gst-discoverer.  If there are no alternative plugins, then gst-discoverer
will fail.  Thus, temporarily change the msdk decode plugins rank to
"primary (256)" so they can be used in gst-discoverer

gst-msdk/transcode: allow msdk plugins to be used by discover

---

lib/gstreamer/encoderbase.py
lib/gstreamer/msdk/encoder.py
lib/gstreamer/msdk/util.py
test/gst-msdk/encode/av1.py

av1-8: gst-msdk added av1 enc cqp lp testing
1, profile map update
2, gstreamer encodebase added tile col and row support
3, gst-msdk add col/row support
4, gst-msdk added av1 implement testing

av1-8: gst-msdk added av1 enc cqp lp testing

---

lib/gstreamer/msdk/transcoder.py
lib/gstreamer/transcoderbase.py
lib/gstreamer/vaapi/transcoder.py

1, gstreamer base support
2, gst-vaapi low power transcode implement
3, gst-msdk low power transcode implement

[Low power transcode] added gst-vaapi/msdk low power transcode support

---

lib/ffmpeg/qsv/transcoder.py
lib/ffmpeg/vaapi/transcoder.py

1, ffmpeg-vaapi lp transcode support
2, ffmpeg-qsv lp transcode support

[Low power transcode] added ffmpeg-vaapi/qsv low power transcode support

---

lib/ffmpeg/qsv/transcoder.py
lib/ffmpeg/transcoderbase.py
lib/ffmpeg/vaapi/transcoder.py

Add a transcoder base class for ffmpeg to share
common code between qsv and vaapi elements.

lib/ffmpeg: add common transcoder base

---

lib/parameters.py
test/ffmpeg-qsv/encode/av1.py

1, core library added av1 8bit lp cbr test parameter
2, ffmpeg-qsv added av1 8 test path implement

ffmpeg qsv added av1 8 enc cbr lp support

---

test/gst-msdk/encode/av1.py

added gst-msdk av1 cbr lp test implement
Signed-off-by: Focus Luo <focus.luo@intel.com>

[AV1] added gst-msdk av1 cbr lp test implement

---

lib/ffmpeg/vaapi/util.py
test/ffmpeg-vaapi/encode/av1.py

1, profile map
2, lp cqp encode
3, lp cbr encode

ffmpeg-vaapi added av1 8bit low power cqp and cbr encode support

---

lib/parameters.py
test/ffmpeg-qsv/encode/av1.py
test/gst-msdk/encode/av1.py

1, parameter in core lib
2, gst-msdk implement
3, ffmpeg-qsv implement

[AV1]  added av1-8 low power vbr encode support for gst-msdk/ffmpeg-qsv

---

lib/ffmpeg/encoderbase.py

Ensure ffmpeg encoder command is compatible with Windows os.
Ensure input and output files are converted to native os
path format.

lib/ffmpeg/encoderbase: use exe2os and filepath2os

---

test/ffmpeg-qsv/encode/av1.py
test/gst-msdk/encode/av1.py

1, ffmpeg-qsv run2run
2, gst-msdk run2run

[Av1] added ffmpeg-qsv and gst-msdk av1 8bit lp encode cqp/cbr/vbr run2run support

---

lib/ffmpeg/qsv/util.py

ffmpeg-qsv can load dxva2 on windows side

dxva support for ffmpeg-qsv

---

lib/ffmpeg/qsv/vpp.py
lib/ffmpeg/transcoderbase.py

vpp transcoder: use exe2os and filepath2os

---

lib/caps/TGL/d3d11
lib/caps/TGL/dxva2

add vdenc encode cases for libvpl and libmfx

lib/caps/TGL: add vdenc encode cases for libvpl and libmfx

---

lib/parameters.py

Adds support for lambdas/functions in format_value.

lib: support lambdas/functions in format_value

---

lib/caps/RKL/d3d11
lib/caps/RKL/dxva2
lib/caps/TGL/d3d11
lib/caps/TGL/dxva2

Caps: add d3d11 dxva2 mainstillpicture for TGL and RKL

---

lib/gstreamer/encoderbase.py

gstreamer muxers write timestamps to container header and
will be different in each r2r iteration.  Thus, extract the
elementary video stream from the container and take md5 on
the elementary video stream.

gst/encoder: take md5 on demuxed video for r2r

---

lib/gstreamer/va/encoder.py
lib/gstreamer/va/util.py
test/gst-va/encode/__init__.py
test/gst-va/encode/avc.py

1, core library support
2, gst-va avc enc profile map
3, gst-va avc testing implement

[gst-va enc] add avc encode support for gst-va

---

lib/ffmpeg/qsv/encoder.py
lib/gstreamer/msdk/encoder.py

Modify the ffmpeg/gst encode frames to meet the bitrate_gap requirements.

lib ffmpeg/gst encoderbase:modify the frames

---

lib/ffmpeg/vaapi/encoder.py

Update ffmpeg-vaapi ipb message for unsupported p-frames

Ffmpeg vaapi ipb msg

---

lib/ffmpeg/encoderbase.py
lib/parameters.py
test/ffmpeg-qsv/encode/avc.py
test/ffmpeg-qsv/encode/hevc.py

Add Intra refresh cases to lib/ffmpeg/encoderbase.

lib/ffmpeg/encoderbase: add Intra refresh cases

---

lib/gstreamer/encoderbase.py
lib/gstreamer/msdk/encoder.py
test/gst-msdk/encode/avc.py
test/gst-msdk/encode/hevc.py

Add intra refresh cases for gst-msdk/encode avc/hevc.

add intra refresh cases for gst-msdk/encode

---

lib/ffmpeg/qsv/encoder.py

Validate more encode test parameters with msgbus output.

ffmpeg/qsv/encode: add more msgbus sanity checks

---

lib/gstreamer/decoderbase.py
lib/gstreamer/encoderbase.py
lib/gstreamer/msdk/util.py
lib/gstreamer/transcoderbase.py
lib/gstreamer/util.py
lib/gstreamer/vppbase.py
test/gst-msdk/general/runtime.py
tools/genassets.py

lib/gstreamer: use exe2os and filepath2os

---

lib/ffmpeg/encoderbase.py

No longer needed according to @wenbinc-Bin

ffmpeg: remove HEVCe bstrategy WA

---

lib/caps/ATSM/iHD
lib/caps/ATSM/info
lib/caps/DG2/iHD
lib/caps/DG2/info

lib/caps: Add DG2 & ATSM

---

test/ffmpeg-vaapi/encode/10bit/vp9.py
test/ffmpeg-vaapi/encode/vp9.py

ffmpeg-vaapi: return vp9 profile based on subsampling

---

lib/ffmpeg/util.py

Since:
https://github.com/FFmpeg/FFmpeg/commit/caf26a8a126d

ffmpeg: map AYUV to vuyx

---

lib/caps/ADL/iHD
lib/caps/ATSM/iHD
lib/caps/DG1/iHD
lib/caps/RKL/iHD
lib/caps/SG1/iHD
lib/caps/TGL/iHD

Since https://github.com/intel/media-driver/commit/0ee16408d53e

caps: gen12 iHD supports DN chroma

---

lib/caps/DG2/d3d11

caps: DG2 add d3d11 support

---

test/gst-va/decode/jpeg.py

gst-va: add jpegd tests

---

lib/ffmpeg/qsv/transcoder.py

Signed-off-by: xinyu dong <xinyux.dong@intel.com>

ffmpeg-qsv: enable vpp lp mode

---

lib/ffmpeg/encoderbase.py
lib/ffmpeg/qsv/encoder.py
lib/parameters.py
test/ffmpeg-qsv/encode/10bit/hevc.py
test/ffmpeg-qsv/encode/avc.py
test/ffmpeg-qsv/encode/hevc.py

This is an example for discussion at https://github.com/intel/vaapi-fits/pull/431#discussion_r941994192
cc: @Wanghangjie8

ffmpeg-qsv: add tcbrc enc tests

---

lib/caps/DG2/d3d11

Signed-off-by: Wang, WenqingX <wenqingx.wang@intel.com>

[caps]:DG2 on windows supports DN chroma

---

lib/ffmpeg/qsv/transcoder.py
lib/ffmpeg/transcoderbase.py
lib/ffmpeg/vaapi/transcoder.py

Signed-off-by: xinyu dong <xinyux.dong@intel.com>

enable vp9 8bit vdenc for ffmpeg

---

lib/gstreamer/va/encoder.py

lib/gst/va/encode: fix typo for the super

---

lib/caps/RKL/d3d11
lib/caps/RKL/dxva2

RKL and TGL should have same caps.

caps: align RKL caps with TGL

---

lib/caps/MTL/iHD
lib/caps/MTL/info

Signed-off-by: Wang Hangjie <hangjiex.wang@intel.com>

[Sanity] add caps/MTL for paltform MTL-P

---

lib/ffmpeg/transcoderbase.py

Signed-off-by: ZhouJian <jian2x.zhou@intel.com>

lib/ffmpeg/transcoderbase.py add HDR test

---

lib/caps/DG2/d3d11

caps: remove yv12 and i420 for DG2 Windows vpp

---

lib/gstreamer/encoderbase.py
lib/gstreamer/msdk/encoder.py
test/gst-msdk/encode/avc.py
test/gst-msdk/encode/hevc.py

gst-msdk: add tcbrc enc tests

---

lib/parameters.py

Signed-off-by: Wang Hangjie <hangjiex.wang@intel.com>

lib/parameters : update lib/parameters

---

lib/ffmpeg/transcoderbase.py

ffmpeg does not have a functional AV1 SW decoder.  Thus, use AV1 HW decoder to do metric check.
This supersedes #473 
cc: @wenqingx

ffmpeg/xcode: use av1 hw decode for check

---

test/gst-msdk/encode/vp9.py

test/gst-msdk/vp9e: add r2r lp tests

---

lib/gstreamer/decoderbase.py
lib/gstreamer/encoderbase.py
lib/gstreamer/msdk/decoder.py
lib/gstreamer/util.py
lib/gstreamer/va/decoder.py
lib/gstreamer/vaapi/decoder.py

Depends on: https://github.com/intel-media-ci/gst-checksumsink/pull/7

gstreamer: inline metrics

---

lib/ffmpeg/qsv/vpp.py
lib/ffmpeg/vaapi/vpp.py
lib/ffmpeg/vppbase.py
lib/mixin/vpp.py
lib/parameters.py
test/ffmpeg-qsv/vpp/stack.py
test/ffmpeg-vaapi/vpp/stack.py

Tests for FFmpeg vaapi and qsv stack filters.

Add FFmpeg VPP Stack Filter Tests

---

test/gst-va/encode/jpeg.py

gst-va add jpeg encodgst-va add jpeg encode test supporte support

[vaapi-fits] gst-va add jpeg encode test support

---

lib/gstreamer/va/encoder.py
test/gst-va/encode/vp9.py

gst-va add vp9 encode test implementation

[gst-va] add vp9 encode test implementation

---

test/gst-va/transcode/hevc.py
test/gst-va/transcode/mpeg2.py

add transcode support for gst-va hevc and mpeg2 input support
1, hevc 8bit input
2, mpeg2 input

[Gst-va] add transcode hevc and mpeg2 support

---

lib/gstreamer/va/vpp.py
test/gst-va/vpp/crop.py

1, core lib support gst-va vpp crop cmdline option
2, added gst-va crop test implement

[Gst-va] add vpp crop support

---

lib/gstreamer/va/encoder.py
test/gst-va/encode/10bit/vp9.py

add vp9 10bit lp encode support

[Gst-va] add vp9 10bit lp encode support

---

lib/gstreamer/msdk/transcoder.py
lib/gstreamer/transcoderbase.py

Add dma cap transcoding case, cmd like:
gst-launch-1.0 -vf filesrc location=input.h264 ! h264parse ! msdkh264dec !"video/x-raw(memory:DMABuf)" ! msdkh264enc ! fakesink

gstmsdk: Add dma caps test case

---

lib/ffmpeg/qsv/transcoder.py
lib/ffmpeg/transcoderbase.py
lib/ffmpeg/vaapi/transcoder.py
test/ffmpeg-qsv/transcode/hevc_h2s.py
test/ffmpeg-vaapi/transcode/hevc_h2s.py

This is used to make sure transcode + tonemaping works as expected.

Transcode hevc h2s

---

lib/gstreamer/util.py
lib/gstreamer/va/encoder.py

This is a workaround for
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/2736

gst-va/enc: maximize va plugin rank

---

lib/gstreamer/va/util.py
lib/gstreamer/va/vpp.py
test/gst-va/vpp/deinterlace.py

1, core lib support for gst-va vpp de-interlace
2, test implement support

[Gst-va] add vpp de-interlace support

---

lib/gstreamer/va/vpp.py

fix typo for return the format string

gst-va: vpp fix mmethod typo

---

lib/gstreamer/vaapi/encoder.py

During gst-vaapi test runs, maximize the rank of the vaapi plugins since
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/2312

gst-vaapi/enc: maximize vaapi plugin rank

---

model/encode/util.py

Pick the model function with the best r-squared value.
Also, add the cubic model function to the choices. The cubic function fits better in some cases.

model/encode: use best r-squared model function

---

lib/caps/TGL/d3d12

Error type: keyword argument repeated.

caps: fix a load caps error

---

tools/trendplot

This script can be used to plot trendline test results from results.xml files.  It may be a useful visualization tool for regression analysis.
cc: @wenqingx

tools: add trendplot script

---

lib/ffmpeg/qsv/encoder.py
model/encode/10bit/__init__.py
model/encode/10bit/hevc.py
test/ffmpeg-qsv/encode/10bit/hevc.py

Add hevc10e trend model support

---

lib/ffmpeg/qsv/encoder.py
lib/ffmpeg/qsv/util.py
lib/ffmpeg/vaapi/encoder.py
lib/ffmpeg/vaapi/util.py
lib/gstreamer/msdk/encoder.py
lib/gstreamer/vaapi/encoder.py
model/encode/10bit/vp9.py
test/ffmpeg-qsv/encode/10bit/vp9.py
test/ffmpeg-vaapi/encode/10bit/vp9.py
test/gst-msdk/encode/10bit/vp9.py
test/gst-va/encode/10bit/vp9.py
test/gst-vaapi/encode/10bit/vp9.py

1, profile map
2, move [ffmpeg/qsv: move VP9-10 Encoder Test classes to lib]
3, add vp9-10 trendline modes

[trendline] added vp9 10bit encode support

---

lib/caps/MTL/iHD
lib/ffmpeg/qsv/encoder.py
lib/parameters.py
test/ffmpeg-qsv/encode/av1.py
test/ffmpeg-vaapi/encode/av1.py
test/gst-msdk/encode/av1.py
test/gst-va/encode/av1.py

add av1-8bit non low power mode support for MTL+ platforms

[MTL+] add av1-8bit non low power mode support

---

lib/caps/MTL/iHD
lib/ffmpeg/qsv/encoder.py
test/ffmpeg-qsv/encode/10bit/av1.py
test/ffmpeg-vaapi/encode/10bit/av1.py
test/gst-msdk/encode/10bit/av1.py
test/gst-va/encode/10bit/av1.py

1, add ffmpeg-vaapi/qsv support
2, add gst-va/msdk support
3, enable in caps

[MTL+] add non-low power mode support for av1 10bit encode

---

baseline/default/test/ffmpeg-qsv/encode/avc.py/cqp_lp.test
baseline/default/test/ffmpeg-vaapi/encode/avc.py/cqp_lp.test
baseline/default/test/gst-msdk/encode/avc.py/cqp_lp.test
baseline/default/test/gst-va/encode/avc.py/cqp_lp.test
baseline/default/test/gst-vaapi/encode/avc.py/cqp_lp.test
config/avc.default

Fixes config load error b/c cqp_lp bframes is required since commit 325f478f563e
Also updated baseline refs.

config/avc: add cqp_lp bframes parameter and update refs

---

requirements.txt

add matplotlib which be used by trend mode

[requirement] add matplotlib

---

lib/ffmpeg/qsv/encoder.py
lib/ffmpeg/vaapi/encoder.py
lib/parameters.py
test/ffmpeg-qsv/encode/av1.py
test/ffmpeg-vaapi/encode/av1.py

1, caps MTL
2, av1-8bit icq parameter
3, ffmpeg-vaapi av1 icq test
4, ffmpeg-qsv av1 icq test
5, trend mode

[av1-8 icq] MTL ffmpeg-vaapi/qsv added av1 8bit ICQ mode support

---

.slashrc
lib/artifacts.py
lib/ffmpeg/decoderbase.py
lib/ffmpeg/encoderbase.py
lib/ffmpeg/transcoderbase.py
lib/ffmpeg/vppbase.py
lib/gstreamer/decoderbase.py
lib/gstreamer/encoderbase.py
lib/gstreamer/transcoderbase.py
lib/gstreamer/vppbase.py
model/encode/util.py
test/self/formats.py

...also add support for session artifacts that will persist for entire test suite run.

Manage artifacts with first-class object

---

lib/gstreamer/msdk/encoder.py
test/gst-msdk/encode/av1.py

1, LP AV1 ICQ mode
2, Non-LP ICQ mode
3, gst-msdk cmd line change

[Icq] gst-msdk added av1-8bit encode ICQ mode support

---

test/ffmpeg-qsv/encode/10bit/av1.py
test/ffmpeg-vaapi/encode/10bit/av1.py
test/gst-msdk/encode/10bit/av1.py

[av1-10 icq] add test support for ffmpeg-vaapi/qsv and gst-msdk

[av1-10 icq] add test support for ffmpeg-vaapi/qsv and gst-msdk

---

lib/parameters.py

gen_av1_cqp_variants
gen_av1_cqp_parameters
gen_av1_vbr_variants
gen_av1_vbr_parameters

lib/parameters.py: cleanup duplicate function:

---

lib/caps/DG2/iHD
lib/formats.py
lib/gstreamer/va/vpp.py
lib/platform.py
test/gst-va/vpp/brightness.py
test/gst-va/vpp/composite.py
test/gst-va/vpp/contrast.py
test/gst-va/vpp/crop.py
test/gst-va/vpp/csc.py
test/gst-va/vpp/deinterlace.py
test/gst-va/vpp/denoise.py
test/gst-va/vpp/hue.py
test/gst-va/vpp/mirroring.py
test/gst-va/vpp/rotation.py
test/gst-va/vpp/saturation.py
test/gst-va/vpp/scale.py
test/gst-va/vpp/sharpen.py
test/gst-va/vpp/transpose.py

Also, fixes wrong spec used for CSC R2R test.

gst-va/vpp: include hwdevice in requires

---

lib/gstreamer/va/transcoder.py

Use correct gst-va element on multi-gpu device

gst-va/xcode: include hwdevice in requirements

---

lib/ffmpeg/qsv/encoder.py
lib/ffmpeg/vaapi/encoder.py
lib/parameters.py
test/ffmpeg-qsv/encode/hevc.py
test/ffmpeg-vaapi/encode/hevc.py

[hevc qvbr] ffmpeg-vaapi and qsv add hevc 8bit qvbr encode support

[hevc qvbr] ffmpeg-vaapi and qsv add hevc 8bit qvbr encode support

---

.slashrc

with new KMD driver XE support add new dmesg keyword for catch error

slashrc: Add Xe driver dmesg filter

---

test/gst-msdk/encode/hevc.py

add gst-msdk hevc-8 qvbr encode test implement

[qvbr] add gst-msdk hevc-8 qvbr encode test implement

---

lib/ffmpeg/vaapi/encoder.py

Revert "[ffmpeg-vaapi] Update FFMPEG-VAAPI Encode AV1 cmd line"

---

lib/ffmpeg/vaapi/encoder.py

[ffmpeg-vaapi] updated FFMPEG-VAAPI encoding AV1 cmd line. 
ffmpeg don't have option about `-icq`

[ffmpeg-vaapi] Address issues introduced by a prior merge.

---

lib/ffmpeg/vaapi/transcoder.py
test/ffmpeg-vaapi/transcode/mpeg2.py

same as https://github.com/intel/vaapi-fits/pull/616 
ffmpeg-vaapi/transcode/mpeg also need “-extra_hw_frames64”, VIZ-20484

ffmpeg-vaapi/transcode/mpeg2 add extra_hw_frames option

---

lib/caps/ADL/iHD
lib/caps/ATSM/iHD
lib/caps/DG2/iHD
lib/caps/RKL/iHD
lib/caps/RPL/iHD
lib/caps/TGL/iHD
lib/ffmpeg/qsv/util.py
lib/ffmpeg/vaapi/encoder.py
lib/ffmpeg/vaapi/util.py
lib/gstreamer/msdk/util.py
lib/gstreamer/va/util.py
lib/gstreamer/vaapi/util.py
model/encode/hevc.py

Added HEVC 8bit 422 encode support for ffmpeg-vaapi/qsv and gst-va/vaapi/msdk

HEVC 8bit 422 encode support

---

lib/ffmpeg/qsv/transcoder.py
lib/ffmpeg/vaapi/transcoder.py
test/ffmpeg-qsv/transcode/mpeg2.py
test/ffmpeg-vaapi/transcode/mpeg2.py

upstream commit
https://github.com/intel-media-ci/ffmpeg/commit/e0da916b8f5b079a4865eef7f64863f50785463d

WA: ffmpeg upstream change increase more buffer about transcode

---

lib/caps/ADL/iHD
lib/caps/ATSM/iHD
lib/caps/DG2/iHD
lib/caps/RKL/iHD
lib/caps/RPL/iHD
lib/caps/SG1/iHD
lib/caps/TGL/iHD
lib/ffmpeg/qsv/util.py
lib/ffmpeg/vaapi/encoder.py
lib/ffmpeg/vaapi/util.py
lib/gstreamer/msdk/util.py
lib/gstreamer/va/util.py
model/encode/10bit/hevc.py

1, trend model
2, caps for Gen12+
3, ffmpeg-qsv, ffmpeg-vaapi, gst-msdk and gst-va add test implement

HEVC 10bit 422 encode support

---

lib/gstreamer/d3d11/__init__.py
lib/gstreamer/d3d11/decoder.py
lib/gstreamer/d3d11/util.py
test/gst-d3d11/__init__.py
test/gst-d3d11/decode/10bit/__init__.py
test/gst-d3d11/decode/10bit/av1.py
test/gst-d3d11/decode/10bit/hevc.py
test/gst-d3d11/decode/10bit/vp9.py
test/gst-d3d11/decode/12bit/__init__.py
test/gst-d3d11/decode/12bit/hevc.py
test/gst-d3d11/decode/12bit/vp9.py
test/gst-d3d11/decode/__init__.py
test/gst-d3d11/decode/av1.py
test/gst-d3d11/decode/avc.py
test/gst-d3d11/decode/hevc.py
test/gst-d3d11/decode/jpeg.py
test/gst-d3d11/decode/mpeg2.py
test/gst-d3d11/decode/vp8.py
test/gst-d3d11/decode/vp9.py

fork form gst-va and just keep for decode part

gst-d3d11: init version to enable gst-d3d11 part test

---

model/encode/12bit/hevc.py

See https://github.com/oneapi-src/oneVPL-intel-gpu/issues/297 for justification

model: update hevc 12bit QP list

---

lib/baseline.py
model/encode/util.py

model: save trend model plots in baseline directory

---

lib/gstreamer/msdk/util.py

https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/6591

gst/msdk: add hevc main-422-12 support 

---

lib/ffmpeg/encoderbase.py

FFmpeg will always encode N frames specified in the -vframes option unless it hits input EOF before N
frames have been read.
We assumed that the input file to the test case only contained N frames specified in the test case config. Thus, we compensated the frame count when setting up the metrics in seek cases... asserting that ffmpeg always hit input EOF.
For example: input = 50 frames, case specifies 50
frames at 25 fps and seek = 1... ffmpeg will only
encode 25 frames even with "-vframes 50".
However, if the input file contains more frames than specified in the test case configuration, then ffmpeg will encode up to N frames after the seek.
For example: input = 150 frames, case specifies 50 frames at 25 fps and seek = 1... ffmpeg will encode 50 frames with "-vframes 50".
Unfortunately, …

ffmpeg/encoder: encode only N minus offset frames after seek

---

lib/gstreamer/transcoderbase.py

gst/xcode: specify decoder fps

---

.github/workflows/unit.yml

...to improve openssf scorecard.

gh/workflows: set top-level permissions

---

.github/dependabot.yml
.github/workflows/unit.yml

These changes will help improve the overall OpenSSF score.
* https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
* https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool

Pin GitHub Action Deps and add Dependabot Config

---

test/ffmpeg-vaapi/decode/10bit/vvc.py
test/ffmpeg-vaapi/decode/vvc.py

VVC native decoder removed experimental flag in master branch

Remove strict property for VVC decoder

---

lib/caps/ADL/d3d11
lib/caps/ADL/d3d12
lib/caps/ADL/dxva2
lib/caps/RPL/d3d11
lib/caps/RPL/d3d12
lib/caps/RPL/dxva2

copy from caps of TGL, please help double check.
@uartie @FocusLuo @feiwan1

[caps] enable ADL/RPL windows support

---

lib/caps/ARL/iHD
lib/caps/ARL/info

[caps] add ARL platform support

[caps] add ARL platform support

---

lib/caps/BMG/d3d11
lib/caps/BMG/d3d12
lib/caps/BMG/iHD
lib/caps/BMG/info
lib/caps/BMG/vaon12

[caps] add BMG platform support

[caps] add BMG platform support

---

lib/caps/LNL/iHD

LNL support decode vp8 feature.

[caps] update LNL iHD caps
